### ISSUE TITLE
你好棒棒哟

### ISSUE THREAD

**Issue by 4679** [coyove/goflyway#1]
![snipaste_20170823_235954](https://user-images.githubusercontent.com/2030404/29625815-5b369e4a-885f-11e7-8995-29593569d908.png)

速度不错哦，虽然比不上v2ray，有没有技术细节啥的(　ﾟ 3ﾟ)

**Comment by coyove** [comment]
代码简单，走的都是基本的HTTP Proxy协议，对关键的header加密（比如Host）。每次请求交换一次新密钥，加密采用的则是非常简单的 xor cipher，因为反正底下承载的流量已经是HTTPS了，我要做的只是加密一下SSL初始握手阶段的明文防止被嗅探到即可。

至于流量监测，要靠第三方的multiplexer混淆。
