### ISSUE TITLE
建议windows编译版本提供监听端口个性化设置

### ISSUE THREAD

**Issue by flyingwhitewhale** [coyove/goflyway#10]
大多数人还是用编译版本多吧。

在编译版本中运行，key和vps-ip可以自己设了
不应用源代码的情况下，本地监听端口怎么个性化呢
刚才试用参数 -L=1080不行

**Comment by coyove** [comment]
`-l=":1080"` 不要忘了前面的冒号

**Comment by flyingwhitewhale** [comment]
@coyove 谢谢大佬这么快回复，试了ok!
不过因为是HTTP代理，不能和SOCKS5-1080共用一个设置，其实个性化端口是没有太大用处。
再次感谢大佬
