### ISSUE TITLE
安卓客户端，显示已连接，但是不能访问

### ISSUE THREAD

**Issue by aikunzhe** [coyove/goflyway#102]
![image](https://user-images.githubusercontent.com/9932394/46239826-d9d48e80-c3d0-11e8-83ef-379423aad984.png)

**Comment by coyove** [comment]
请使用 adb logcat -s GuardedProcess 输出错误日志

**Comment by aikunzhe** [comment]
最新版的， 客户端，服务器也是，用的是cdn模式， PC端可以正常使用

**Comment by coyove** [comment]
看日志，你的密码没有按照wiki里写
https://github.com/coyove/goflyway/wiki/Cloudflare-%E7%9B%B8%E5%85%B3

**Comment by aikunzhe** [comment]
按照文档来修改，也就是 只要知道我的域名 就可以用了？[/捂脸]

**Comment by aikunzhe** [comment]
蟹蟹作者 已经可以了。
