### ISSUE TITLE
what's the fking problem?

### ISSUE THREAD

**Issue by Handsome1080P** [coyove/goflyway#106]
![TIM截图20180930204050.png](https://i.loli.net/2018/09/30/5bb0c469a7ea7.png)
i am building for arm64,using command this
GOOS=linux GOARCH=arm64 go build -o build/goflyway cmd/goflyway/main.go

**Comment by Handsome1080P** [comment]
![TIM截图20180930205353.png](https://i.loli.net/2018/09/30/5bb0c785b290d.png)
![TIM截图20180930205400.png](https://i.loli.net/2018/09/30/5bb0c785cbdb1.png)

**Comment by coyove** [comment]
请阅读readme，并了解一下:https://stackoverflow.com/questions/32758235/how-to-get-all-dependency-files-for-a-program-using-golang
