### ISSUE TITLE
Compile on arm devices

### ISSUE THREAD

**Issue by Handsome1080P** [coyove/goflyway#107]
![TIM截图20180930213859.png](https://i.loli.net/2018/09/30/5bb0d244764b5.png)
![TIM截图20180930213933.png](https://i.loli.net/2018/09/30/5bb0d244bd279.png)
![TIM截图20180930214004.png](https://i.loli.net/2018/09/30/5bb0d244bbd3e.png)
![TIM截图20180930213634.png](https://i.loli.net/2018/09/30/5bb0d244bf7c2.png)

**Comment by Handsome1080P** [comment]
all downloaded,still notworking

**Comment by Handsome1080P** [comment]
pls give me a correct way to solve this fking problem

**Comment by hiboyhiboy** [comment]
cd "$GOPATH"/src/github.com/coyove/tcpmux
git reset --hard
git checkout dev
git pull

**Comment by hiboyhiboy** [comment]
cd "$GOPATH"/src/github.com/coyove/goflyway
git reset --hard
git checkout gdev
git pull

**Comment by Handsome1080P** [comment]
> cd "$GOPATH"/src/github.com/coyove/goflyway
> git reset --hard
> git checkout gdev
> git pull

same problem

**Comment by Handsome1080P** [comment]
![TIM截图20181001133031.png](https://i.loli.net/2018/10/01/5bb1b11096e19.png)

**Comment by Handsome1080P** [comment]
what's the fking noob coding?!

**Comment by Handsome1080P** [comment]
this is the way to solve this problem.U can build this program on arm devices.
ALL COMMANDS ONLY IN GOPATH TO RUN.
1. git all things to ur devices.use follow command.
`go get -d github.com/coyove/goflyway/cmd/goflyway`
2.go ur GOPATH folder,then cd it.
`cd  /src/github.com/coyove/tcpmux`
3.switch tcpmux to dev branch
`git checkout`
4.back to coyove folder.
`cd src/github.com/coyove/goflyway/ `
5.build,u can set arm,arm64,etc.
`GOOS=linux GOARCH=arm  go build -o build/goflyway cmd/goflyway/main.go`
6.file in src/github.com/coyove/goflyway/build
