### ISSUE TITLE
proxy.Logger.E("args...")

### ISSUE THREAD

**Issue by hiboyhiboy** [coyove/goflyway#108]
https://github.com/coyove/goflyway/blob/5ddf5b600f572634b4ef79428ade8c0949484b25/proxy/client.go#L470

proxy.Logger.E("args...")

**Comment by Handsome1080P** [comment]
same problem.and more errors
![TIM截图20181001133031.png](https://i.loli.net/2018/10/01/5bb1b11096e19.png)

**Comment by coyove** [comment]
目前请在goflyway的master branch下工作

**Comment by Handsome1080P** [comment]
> 目前请在goflyway的master branch下工作
same problem
[![TIM截图20181001202950.png](https://i.loli.net/2018/10/01/5bb2134c7a2bf.png)](https://i.loli.net/2018/10/01/5bb2134c7a2bf.png)

**Comment by coyove** [comment]
tcpmux需要在dev branch下

**Comment by Handsome1080P** [comment]
> tcpmux需要在dev branch下

which one i need switch?
![TIM截图20181001213438.png](https://i.loli.net/2018/10/01/5bb222734e084.png)

**Comment by Handsome1080P** [comment]
or i need to compile twice in master and gdev？

**Comment by Handsome1080P** [comment]
switch tcpmux to dev branch,it's works!
