### ISSUE TITLE
 goflyway linux client上无法使用cloudflare连接到linux goflyway server

### ISSUE THREAD

**Issue by zqw86713** [coyove/goflyway#109]
有没有人和我一样，在linux goflyway client上无法使用cdn连接到linux goflyway server的？

**Comment by zqw86713** [comment]
经三次以上的确认，我在Linux client上使用的命令如下 ，环境为debian 9 x86_64.

当我使用CDN的方法时，是无法连接上goflyway server的。
`./goflyway -k=1234 up="cf:/abc.com:2095" -g`

当我使用IP的方式时，是可以正常连接的。
./goflyway -k=1234 -up="1.2.3.4:2095" -g

我不会导出debug日志，可否请开发者告之我具体的命令？ 是否是 
`./goflyway -k=1234 -up="1.2.3.4:2095" -g -lv dbg > debug.txt`

**Comment by coyove** [comment]
日志是打到stderr上的，所以需要用`2>&1`

**Comment by zqw86713** [comment]
root@zhenjiang:~/goflyway# ./goflyway -up="cf://abc.com:2095" -k="83529174" -l=":8100" -web-port="8101" -lv=log -g -U=http
2018-10-04 09:35:51.037 CST,main.go:266,  LOG  ,Build,goflyway 180927033307
2018-10-04 09:35:51.038 CST,main.go:269,  LOG  ,Role,Client
2018-10-04 09:35:51.156 CST,main.go:299,  LOG  ,ACL,Source,chinalist.txt
2018-10-04 09:35:51.156 CST,main.go:466,  LOG  ,Upstream,cf://abc.com:2095
2018-10-04 09:35:51.157 CST,main.go:483,  LOG  ,Cloudflare,abc.com:2095
2018-10-04 09:35:51.157 CST,main.go:493,  LOG  ,Dial,Server,abc.com:2095
2018-10-04 09:35:51.157 CST,main.go:498,  LOG  ,Websocket,Enabled
2018-10-04 09:35:51.157 CST,main.go:328,  LOG  ,Global Proxy,Enabled
2018-10-04 09:35:51.157 CST,main.go:404,  LOG  ,Alias,DC218B
2018-10-04 09:35:51.158 CST,main.go:407,  LOG  ,Client,Dial,abc.com:2095
2018-10-04 09:35:51.158 CST,main.go:445,  LOG  ,Client,Proxy started,0.0.0.0:8100
2018-10-04 09:35:51.158 CST,main.go:441,  LOG  ,Client,Web console,127.0.0.1:8101
2018-10-04 09:35:59.133 CST,httpmux.go:39,  ERROR  ,HTTP/SOCKS,Prefetch,"read 64.231.105.254:56295, i/o timeout"
2018-10-04 09:36:01.133 CST,httpmux.go:39,  ERROR  ,HTTP/SOCKS,Prefetch,"read 64.231.105.254:56299, i/o timeout"
2018-10-04 09:36:03.134 CST,httpmux.go:39,  ERROR  ,HTTP/SOCKS,Prefetch,"read 64.231.105.254:56305, i/o timeout"
2018-10-04 09:36:04.129 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56319, C104, read: connection reset by peer"
2018-10-04 09:36:04.200 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56322, C104, read: connection reset by peer"
2018-10-04 09:36:07.606 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56347, C104, read: connection reset by peer"
2018-10-04 09:36:08.098 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56360, C104, read: connection reset by peer"
2018-10-04 09:36:15.111 CST,httpmux.go:39,  ERROR  ,HTTP/SOCKS,Prefetch,"read 64.231.105.254:56422, i/o timeout"
2018-10-04 09:36:15.951 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56424, C104, read: connection reset by peer"
2018-10-04 09:36:17.112 CST,httpmux.go:39,  ERROR  ,HTTP/SOCKS,Prefetch,"read 64.231.105.254:56433, i/o timeout"
2018-10-04 09:36:51.628 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56543, C104, read: connection reset by peer"
2018-10-04 09:36:51.645 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56544, C104, read: connection reset by peer"
2018-10-04 09:37:01.301 CST,io.go:85,  ERROR  ,Bridge,"read 64.231.105.254:56569, C104, read: connection reset by peer"

**Comment by zqw86713** [comment]
以上是我的日志。

以下是我运行的命令，
`./goflyway -up="cf://abc.com:2095" -k="1234" -l=":8100" -web-port="8101" -lv=log -g -U=http`

在命令运行后，大约10秒之内可以连接server，10秒之后就无法连接上server。

**Comment by coyove** [comment]
`64.231.105.254` 是什么？

**Comment by zqw86713** [comment]
是我 的IP地址。我人在加拿大，所以我是用国内的一台VPS运行goflyway server，然后我在加拿大用http proxy的方式去连接VPS 的8100端口

**Comment by coyove** [comment]
登陆client所在的vps，保留你输入的命令，后面加上： `-get https://google.com`，如果成功代表服务端没有问题。

**Comment by zqw86713** [comment]
`./goflyway -up="cf://superla.stream:2095" -k="83529174" -l=":8100" -web-port="8101" -lv=log -g -U=http -get https://www.google.com
2018-10-04 09:54:19.580 CST,main.go:266,  LOG  ,Build,goflyway 180927033307
2018-10-04 09:54:19.580 CST,main.go:269,  LOG  ,Role,Client
2018-10-04 09:54:19.697 CST,main.go:299,  LOG  ,ACL,Source,chinalist.txt
2018-10-04 09:54:19.698 CST,main.go:466,  LOG  ,Upstream,cf://superla.stream:2095
2018-10-04 09:54:19.698 CST,main.go:483,  LOG  ,Cloudflare,superla.stream:2095
2018-10-04 09:54:19.698 CST,main.go:493,  LOG  ,Dial,Server,superla.stream:2095
2018-10-04 09:54:19.698 CST,main.go:498,  LOG  ,Websocket,Enabled
2018-10-04 09:54:19.698 CST,main.go:328,  LOG  ,Global Proxy,Enabled
2018-10-04 09:54:19.698 CST,main.go:404,  LOG  ,Alias,DC218B
2018-10-04 09:54:19.699 CST,main.go:407,  LOG  ,Client,Dial,superla.stream:2095
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="zh-HK"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="d2SL+KJTOSIY+4SiZ3uhZw==">(function(){window.google={kEI:'zHK1W_7bE5OOvQSBiKSoCg',kEXPI:'0,18167,1335579,58,51,1907,582,434,282,1124,1225,731,141,248,228,362,421,96,62,438,62,232,62,427,2337325,245,32,302989,26305,1294,12383,4855,32691,15248,867,6692,5471,5281,1953,5689,1402,2196,369,1100,438,4090,3191,1241,1201,260,1028,2549,1530,575,830,3,286,2,578,728,2431,1362,1712,28,2130,453,2096,1294,8,960,609,223,551,1232,883,135,281,2,1718,2348,395,7,518,22,604,2,1766,199,61,467,3,773,1293,4,176,283,585,3151,69,1050,334,11,119,1110,234,386,8,1003,81,7,29,462,421,199,29,1031,348,462,5,7,62,569,1315,1258,859,119,1061,1068,46,78,375,339,141,604,244,9,304,876,404,8,2,198,357,78,428,1112,30,610,41,62,2,270,18,255,108,1,994,2,237,58,43,72,70,978,37,184,202,66,251,485,71,141,93,173,8,440,178,175,159,279,102,37,349,475,159,196,151,150,2,332,47,634,436,33,137,186,1030,105,8,89,91,754,17,5,5,1,5991840,2553,5997691,2800095,4,1572,549,332,445,1,2,1,1,78,1,900,579,6,311,1,8,1,2,1,1,2130,1,1,1,1,1,414,1,263,49,39,20,15,3,2,2,2,242,1,66,1,6,8,29,9,65,7,17,5,45,31,5',authuser:0,kscs:'c9c918f0_zHK1W_7bE5OOvQSBiKSoCg',kGL:'HK'};google.kHL='zh-HK';})();google.time=function(){return(new Date).getTime()};(function(){google.lc=[];google.li=0;google.getEI=function(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||google.kEI};google.getLEI=function(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b};google.https=function(){return"https:"==window.location.protocol};google.ml=function(){return null};google.log=function(a,b,e,c,g){if(a=google.logUrl(a,b,e,c,g)){b=new Image;var d=google.lc,f=google.li;d[f]=b;b.onerror=b.onload=b.onabort=function(){delete d[f]};google.vel&&google.vel.lu&&google.vel.lu(a);b.src=a;google.li=f+1}};google.logUrl=function(a,b,e,c,g){var d="",f=google.ls||"";e||-1!=b.search("&ei=")||(d="&ei="+google.getEI(c),-1==b.search("&lei=")&&(c=google.getLEI(c))&&(d+="&lei="+c));c="";!e&&google.cshid&&-1==b.search("&cshid=")&&"slh"!=a&&(c="&cshid="+google.cshid);a=e||"/"+(g||"gen_204")+"?atyp=i&ct="+a+"&cad="+b+d+f+"&zx="+google.time()+c;/^http:/i.test(a)&&google.https()&&(google.ml(Error("a"),!1,{src:a,glmm:1}),a="");return a};}).call(this);(function(){google.y={};google.x=function(a,b){if(a)var c=a.id;else{do c=Math.random();while(google.y[c])}google.y[c]=[a,b];return!1};google.lm=[];google.plm=function(a){google.lm.push.apply(google.lm,a)};google.lq=[];google.load=function(a,b,c){google.lq.push([[a],b,c])};google.loadAll=function(a,b){google.lq.push([a,b])};}).call(this);google.f={};</script><script nonce="d2SL+KJTOSIY+4SiZ3uhZw==">var a=window.location,b=a.href.indexOf("#");if(0<=b){var c=a.href.substring(b+1);/(^|&)q=/.test(c)&&-1==c.indexOf("#")&&a.replace("/search?"+c.replace(/(^|&)fp=[^&]*/g,"")+"&cad=h")};</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#36c}.q{color:#00c}.ts td{padding:0}.ts{border-collapse:collapse}em{color:#c03;font-style:normal;font-weight:normal}a em{text-decoration:underline}.lst{height:25px;width:496px}.gsfi,.lst{font:18px arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}a.gb1,a.gb2,a.gb3,a.gb4{color:#11c !important}body{background:#fff;color:black}a{color:#11c;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#36c}a:visited{color:#551a8b}a.gb1,a.gb4{text-decoration:underline}a.gb3:hover{text-decoration:none}#ghead a.gb2:hover{color:#fff !important}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-size:11px}.lsbb{background:#eee;border:solid 1px;border-color:#ccc #999 #999 #ccc;height:30px}.lsbb{display:block}.ftl,#fll a{display:inline-block;margin:0 12px}.lsb{background:url(/images/nav_logo229.png) 0 -261px repeat-x;border:none;color:#000;cursor:pointer;height:30px;margin:0;outline:0;font:15px arial,sans-serif;vertical-align:top}.lsb:active{background:#ccc}.lst:focus{outline:none}</style><script nonce="d2SL+KJTOSIY+4SiZ3uhZw=="></script></head><body bgcolor="#fff"><script nonce="d2SL+KJTOSIY+4SiZ3uhZw==">(function(){var src='/images/nav_logo229.png';var iesg=false;document.body.onload = function(){window.n && window.n();if (document.images){new Image().src=src;}
if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"> <div id=gbar><nobr><b class=gb1>&#25628;&#23563;</b> <a class=gb1 href="https://www.google.com.hk/imghp?hl=zh-TW&tab=wi">&#22294;&#29255;</a> <a class=gb1 href="https://maps.google.com.hk/maps?hl=zh-TW&tab=wl">&#22320;&#22294;</a> <a class=gb1 href="https://play.google.com/?hl=zh-TW&tab=w8">Play</a> <a class=gb1 href="https://www.youtube.com/?gl=HK&tab=w1">YouTube</a> <a class=gb1 href="https://news.google.com.hk/nwshp?hl=zh-TW&tab=wn">&#26032;&#32862;</a> <a class=gb1 href="https://mail.google.com/mail/?tab=wm">Gmail</a> <a class=gb1 href="https://drive.google.com/?tab=wo">&#38642;&#31471;&#30828;&#30879;</a> <a class=gb1 style="text-decoration:none" href="https://www.google.com.hk/intl/zh-TW/options/"><u>&#26356;&#22810;</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a href="http://www.google.com.hk/history/optout?hl=zh-TW" class=gb4>&#32178;&#38913;&#35352;&#37636;</a> | <a  href="/preferences?hl=zh-TW" class=gb4>&#35373;&#23450;</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=zh-TW&passive=true&continue=https://www.google.com/" class=gb4>&#30331;&#20837;</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div> </div><center><br clear="all" id="lgpd"><div id="lga"><img alt="Google" height="92" src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png" style="padding:28px 0 14px" width="272" id="hplogo" onload="window.lol&&lol()"><br><br></div><form action="/search" name="f"><table cellpadding="0" cellspacing="0"><tr valign="top"><td width="25%">&nbsp;</td><td align="center" nowrap=""><input name="ie" value="ISO-8859-1" type="hidden"><input value="zh-HK" name="hl" type="hidden"><input name="source" type="hidden" value="hp"><input name="biw" type="hidden"><input name="bih" type="hidden"><div class="ds" style="height:32px;margin:4px 0"><input style="color:#000;margin:0;padding:5px 8px 0 6px;vertical-align:top" autocomplete="off" class="lst" value="" title="Google &#25628;&#23563;" maxlength="2048" name="q" size="57"></div><br style="line-height:0"><span class="ds"><span class="lsbb"><input class="lsb" value="Google &#25628;&#23563;" name="btnG" type="submit"></span></span><span class="ds"><span class="lsbb"><input class="lsb" value="&#22909;&#25163;&#27683;" name="btnI" onclick="if(this.form.q.value)this.checked=1; else top.location='/doodles/'" type="submit"></span></span></td><td class="fl sblc" align="left" nowrap="" width="25%"><a href="/advanced_search?hl=zh-HK&amp;authuser=0">&#36914;&#38542;&#25628;&#23563;</a><a href="/language_tools?hl=zh-HK&amp;authuser=0">&#35486;&#35328;&#24037;&#20855;</a></td></tr></table><input id="gbv" name="gbv" type="hidden" value="1"><script nonce="d2SL+KJTOSIY+4SiZ3uhZw==">(function(){var a,b="1";if(document&&document.getElementById)if("undefined"!=typeof XMLHttpRequest)b="2";else if("undefined"!=typeof ActiveXObject){var c,d,e=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];for(c=0;d=e[c++];)try{new ActiveXObject(d),b="2"}catch(h){}}a=b;if("2"==a&&-1==location.search.indexOf("&gbv=2")){var f=google.gbvu,g=document.getElementById("gbv");g&&(g.value=a);f&&window.setTimeout(function(){location.href=f},0)};}).call(this);</script></form><div id="gac_scont"></div><div style="font-size:83%;min-height:3.5em"><br><div id="gws-output-pages-elements-homepage_additional_languages__als"><style>#gws-output-pages-elements-homepage_additional_languages__als{font-size:small;margin-bottom:24px}#SIvCob{display:inline-block;line-height:28px;}#SIvCob a{padding:0 3px;}.H6sW5{display:inline-block;margin:0 2px;white-space:nowrap}.z4hgWe{display:inline-block;margin:0 2px}</style><div id="SIvCob">Google &#25552;&#20379;&#65306;  <a href="https://www.google.com/setprefs?sig=0_r62k8bmhL1DAcRExKNBZ_ZYM_KA%3D&amp;hl=zh-CN&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj-8bj31uvdAhUTR48KHQEECaUQ2ZgBCAU">&#20013;&#25991;(&#31616;&#20307;)</a>    <a href="https://www.google.com/setprefs?sig=0_r62k8bmhL1DAcRExKNBZ_ZYM_KA%3D&amp;hl=en&amp;source=homepage&amp;sa=X&amp;ved=0ahUKEwj-8bj31uvdAhUTR48KHQEECaUQ2ZgBCAY">English</a>  </div></div></div><span id="footer"><div style="font-size:10pt"><div style="margin:19px auto;text-align:center" id="fll"><a href="/intl/zh-TW/ads/">&#24291;&#21578;&#26381;&#21209;</a><a href="/intl/zh-TW/about.html">Google &#23436;&#20840;&#25163;&#20874;</a><a href="https://www.google.com/setprefdomain?prefdom=HK&amp;prev=https://www.google.com.hk/&amp;sig=K_hizrHw0qk2nd22HSsNW2Oieg-a0%3D">Google.com.hk</a></div></div><p style="color:#767676;font-size:8pt">&copy; 2018 - <a href="/intl/zh-TW/policies/privacy/">&#31169;&#38577;&#27402;&#25919;&#31574;</a> - <a href="/intl/zh-TW/policies/terms/">&#26781;&#27454;</a></p></span></center><script nonce="d2SL+KJTOSIY+4SiZ3uhZw==">(function(){window.google.cdo={height:0,width:0};(function(){var a=window.innerWidth,b=window.innerHeight;if(!a||!b){var c=window.document,d="CSS1Compat"==c.compatMode?c.documentElement:c.body;a=d.clientWidth;b=d.clientHeight}a&&b&&(a!=google.cdo.width||b!=google.cdo.height)&&google.log("","","/client_204?&atyp=i&biw="+a+"&bih="+b+"&ei="+google.kEI);}).call(this);})();</script><div id="xjsd"></div><div id="xjsi"><script nonce="d2SL+KJTOSIY+4SiZ3uhZw==">(function(){function c(b){window.setTimeout(function(){var a=document.createElement("script");a.src=b;google.timers&&google.timers.load.t&&google.tick&&google.tick("load",{gen204:"xjsls",clearcut:31});document.getElementById("xjsd").appendChild(a)},0)}google.dljp=function(b,a){google.xjsu=b;c(a)};google.dlj=c;}).call(this);if(!google.xjs){window._=window._||{};window._DumpException=window._._DumpException=function(e){throw e};window._F_installCss=window._._F_installCss=function(c){};google.dljp('/xjs/_/js/k\x3dxjs.hp.en.w6xPAr8Tpu4.O/m\x3dsb_he,d/am\x3dYmA2/rt\x3dj/d\x3d1/rs\x3dACT90oEb_Ea9uwsfl7OBw3BLY8hfKHaD6w','/xjs/_/js/k\x3dxjs.hp.en.w6xPAr8Tpu4.O/m\x3dsb_he,d/am\x3dYmA2/rt\x3dj/d\x3d1/rs\x3dACT90oEb_Ea9uwsfl7OBw3BLY8hfKHaD6w');google.xjs=1;}google.pmc={"sb_he":{"agen":true,"cgen":true,"client":"heirloom-hp","dh":true,"dhqt":true,"ds":"","ffql":"zh-TW","fl":true,"host":"google.com","isbh":28,"msgs":{"cibl":"&#28165;&#38500;&#25628;&#23563;","dym":"&#24744;&#26159;&#19981;&#26159;&#35201;&#26597;&#65306;","lcky":"&#22909;&#25163;&#27683;","lml":"&#30637;&#35299;&#35443;&#24773;","oskt":"&#36664;&#20837;&#24037;&#20855;","psrc":"&#24050;&#24478;&#24744;&#30340;&#12300;\u003Ca href=\"/history\"\u003E&#32178;&#38913;&#35352;&#37636;\u003C/a\u003E&#12301;&#20013;&#31227;&#38500;&#36889;&#31558;&#25628;&#23563;&#35352;&#37636;","psrl":"&#31227;&#38500;","sbit":"&#20197;&#22294;&#25628;&#23563;","srch":"Google &#25628;&#23563;"},"ovr":{},"pq":"","refpd":true,"refspre":true,"rfs":[],"sbpl":24,"sbpr":24,"scd":10,"sce":5,"stok":"hNmzu0y9Kal2nKx6jvPeZMDsJMI","uhde":false},"d":{},"ZI/YVQ":{},"Qnk92g":{},"U5B21g":{},"DPBNMg":{},"YFCs/g":{}};google.x(null,function(){});(function(){var r=[];google.plm(r);})();(function(){var m=[]
;google.jsc && google.jsc.m(m);})();</script></div></body></html>2018-10-04 09:54:20.603 CST,main.go:641,  LOG  ,CURL,Completed in 0.904s
root@zhenjiang:~/goflyway#
`

**Comment by zqw86713** [comment]
谢谢你的回答。我按照你的说去做了，然后把log上传了。以上就是Log.

**Comment by coyove** [comment]
从输出看，客户端和服务端都没有问题，从加拿大连镇江时出现问题。

**Comment by zqw86713** [comment]
是这样吗？好的。那我让国内的朋友，使用http proxy 来连接我的client，看能不能连接上。

谢谢你的解答。这个软件很有用。

**Comment by zqw86713** [comment]
problem solved, case closed.
