### ISSUE TITLE
 operation timed out

### ISSUE THREAD

**Issue by efanng** [coyove/goflyway#11]
![qq20170912-134817](https://user-images.githubusercontent.com/1562932/30310083-2f7290d6-97c1-11e7-8161-c467b4baa60c.png)

**Comment by coyove** [comment]
从描述上看是getsockopt的问题，其他网页是否工作正常？

**Comment by efanng** [comment]
@coyove 我测试了几个常用的几个境外网站都不行。不知道是不是我这边的宽带原因。这几天shadowsocks所有节点都没法用。地点上海。

**Comment by Necromance** [comment]
@efanng  我试用了下，似乎只有console里列出ip地址的那些网站可以正常访问，比如我google上的去，facebook，twitter就不行

**Comment by coyove** [comment]
@Necromance @efanng 服务端是否有什么输出

**Comment by efanng** [comment]
@coyove 我直接在本机上测试的

**Comment by coyove** [comment]
服务端也在本地？

**Comment by efanng** [comment]
@coyove 是的

**Comment by coyove** [comment]
服务端也在本地？

**Comment by coyove** [comment]
那连不上google.com不是很正常吗。。XD

**Comment by efanng** [comment]
@coyove 运行了goflyway，而且也设置了127.0.0.1:8100代理了

**Comment by efanng** [comment]
@coyove 好吧，我知道了。

**Comment by coyove** [comment]
如果服务端也在墙内，那怎么连墙外的网站呢

**Comment by efanng** [comment]
@coyove 我想错了，在微博上看到的，还挺惊讶。不过如果有一台LinuxVPS，可以直接使用SSH Proxy。
![qq20170912-154743](https://user-images.githubusercontent.com/1562932/30313969-c8f69148-97d1-11e7-9636-27e647ac2501.png)

**Comment by coyove** [comment]
除了改host，现在哪有不靠境外服务器的方法┑(￣Д ￣)┍
