### ISSUE TITLE
github.com/coyove/goflyway/proxy/io.go:106:9: undefined: tcpmux.Survey

### ISSUE THREAD

**Issue by koolwiki** [coyove/goflyway#111]
如题，最近tcpmux的第[540c6ed](https://github.com/coyove/tcpmux/commit/514069ba87ab76de2d3322e6b79bb88f24aa4b06)号提交中删掉了util.go中：
type Survey interface {
	Count() []int
}

导致goflyway编译出现题目中的错误，希望能帮忙修复，谢谢！

**Comment by coyove** [comment]
Fixed, please git pull
