### ISSUE TITLE
invalid websocket response: 522 Origin Connection Time-out 

### ISSUE THREAD

**Issue by B1ue-Sky** [coyove/goflyway#119]
**use cloudflare before server. port ~8000,http mode
but got error when check connecting to bing.com:
so where is broken  in the connection path? (server? CF -> server? or me -> CF?) **
(use $ symbol hide private info)

> client.go:394, ERROR ,"Dial failed: invalid websocket response from bing.com:443: HTTP/1.1 522 Origin Connection Time-out
> Date: Sun, $ Nov 2018 $$:$$:$$ GMT
> Content-Type: text/html; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=$$$; expires=$-Nov-19 $$:$$:$$ GMT; path=/; domain=$$$; HttpOnly
> Set-Cookie: cf_use_ob=0; path=/; expires=$-Nov-18 $$:$$:$$ GMT
> Expires: Thu, 01 Jan 1970 00:00:01 GMT
> Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
> Pragma: no-cache
> Server: cloudflare
> CF-RAY: $$$
>

**Comment by B1ue-Sky** [comment]
cmdline: -up="cf://$$:$$" -k="$$$$" -l=":8100" -web-port="8101" -lv=dbg -g -U=http 
version: v2.0.0 rc1 win x86_64
Thanks!

**Comment by coyove** [comment]
`522 Origin Connection Time-out` means cloudflare can't connect to your server

**Comment by B1ue-Sky** [comment]
Confirmed. Thanks!

**Comment by foreverlms** [comment]
@binus Hi, How do you solve this error?
