### ISSUE TITLE
Software caused connection abort

### ISSUE THREAD

**Issue by B1ue-Sky** [coyove/goflyway#122]
`
2018-11-15 $$$,client.go:390, LOG ,Global - bing.com:443

2018-11-15 $$$,io.go:83, ERROR ,"Bridge: read 127.0.0.1:17857, Software caused connection abort"

...

2018-11-15 $$$,client.go:486, ERROR ,SOCKS5 version error: 4
`
cmd:goflyway.exe -up="cf://$$$:80" -k="$$$" -l=":8100" -web-port="8101" -lv=dbg -g -U=http
plat: win10 x64
Rev:fa7eda0

Thanks for any clue about this problem.

**Comment by coyove** [comment]
This error normally doesn't matter

**Comment by B1ue-Sky** [comment]
Thanks. this error Indeed doesn't matter and wait some minutes before seeing the real error log.

(BTW: the real problem is about dns. local dns give fake ipv6 addr so that can't connect. (don't know why DNScrypt didn't work)
disable system ipv6 module and solved :(
Thanks again and maybe one day the dns problem will be solved gracefully.)
