### ISSUE TITLE
那个，能够问一下大佬，CDN模式支持https吗？如果可以的话该怎么做，谢谢

### ISSUE THREAD

**Issue by qiyuanshijie** [coyove/goflyway#135]
那个，嗯没错，我的服务器确实性能有所剩余，而且作为一个看视频，和science论文为主的，对于ping，没有要求。所以，为了提高安全性，还是希望大佬能够说明一下在CDN模式下启用https。
（虽然知道这么说很不负责任，但是，，，，，，谢谢）

**Comment by coyove** [comment]
客户端启用`-U https`，服务端依照cloudflare的设置，如果是strict也要启用`-U https`。连接用：`cf://example.com:443`
http模式和https模式安全性其实没有本质区别

**Comment by qiyuanshijie** [comment]
谢谢，我一直以为那个https指的是通过ssl进行加密。

**Comment by coyove** [comment]
https模式确实是使用tls的，但在已有的加密模式上在加密一次，就是我所说的“没有本质区别”
