### ISSUE TITLE
安卓版是否支持kcp，电信网表示cdn模式无法正常使用

### ISSUE THREAD

**Issue by shf4715** [coyove/goflyway#136]

**Comment by coyove** [comment]
1. 不支持
2. CDN模式下的错误日志是什么？

**Comment by shf4715** [comment]
可能是运营商网络问题，今天已恢复正常。感谢作者！

**Comment by shf4715** [comment]
2019-03-17 23:43:31.146 CST,io.go:84, ERROR ,"Bridge: write myserverip:80, C32, write: broken pipe"

**Comment by shf4715** [comment]
服务端此时没有任何日志

**Comment by maiapig** [comment]
…我也是 移动4g可以用 电信4g和电信宽带的wifi不能用 电信pc端没问题
