### ISSUE TITLE
能使用非 cloudflare 的CDN吗？

### ISSUE THREAD

**Issue by gaoyuoppa** [coyove/goflyway#152]
用其他家的收费Cdn可不可以加快一些速度？
如何使用其他家的Cdn？

**Comment by 1608637229** [comment]
问一下你们都是用这个软件套CDN吗。我这两天被封了两个ip。所以找其他工具找到了这个软件。
好像这软件只是简单的头加密(我也不懂)，看其他的v2ray和ss都有各种加密方法。这个软件是靠什么来
防止gfw的探知的？

**Comment by gaoyuoppa** [comment]
我是套的，不套不放心

**Comment by gaoyuoppa** [comment]
请教下哦。有一些香港的CDN，用的话，是不是会比CF快呢？

**Comment by coyove** [comment]
如果支持websocket就可以（比如cloudfront）
或者使用master branch的版本，则任何cdn基本都可以

**Comment by gaoyuoppa** [comment]
谢谢解答，请问master branch的版本使用的是 cmd的启动命令是什么？第三方cdn,cf 好像不可以诶
