### ISSUE TITLE
编译的时候 goflyway/ssvpn_windows.go 报错

### ISSUE THREAD

**Issue by pchaos** [coyove/goflyway#161]
maset分支,编译的时候 goflyway/ssvpn_windows.go 报错
找不到目录："github.com/coyove/goflyway/pkg/trafficmon"

**Comment by pchaos** [comment]
应该是没设置go环境

**Comment by nbuhell** [comment]
把1.0版本的代码 pkg 复制到gopath对应的目录下就可以编译了

**Comment by pchaos** [comment]
故意不放pkg的吗？
