### ISSUE TITLE
还是Ipv6问题

### ISSUE THREAD

**Issue by gaoyuoppa** [coyove/goflyway#168]
一台机器好几个IPv6。比如:
    2607:f0d0:1003:1::11
    2607:f0d0:1003:1::12
    2607:f0d0:1003:1::13
等，但是访问的时候，显示的IPv6地址，总是最后添加的一个。
比如：-up="[2607:f0d0:1003:1::11]:80"
但是显示的地址是： 2607:f0d0:1003:1::13

这种是正常的吗？

**Comment by coyove** [comment]
> 但是显示的地址是： 2607:f0d0:1003:1::13
是什么意思？日志里面输出的吗？
服务端绑定在了`2607:f0d0:1003:1::11`上？

**Comment by gaoyuoppa** [comment]
比如，服务器启动的是 2607:f0d0:1003:1::11 ，
客户端启动的也是 2607:f0d0:1003:1::11

但是通过第网站查询 http://test-ipv6.com/ 查询，
显示的地址是最后一个添加的：2607:f0d0:1003:1::13

**Comment by coyove** [comment]
```
        2607:f0d0:1003:1::11          2607:f0d0:1003:1::13
Client ---------->----------- Server ---------->----------- test-ipv6.com
```
客户端连服务端的IP 与 服务端连目标网站的IP 是没有关系的

**Comment by gaoyuoppa** [comment]
好的，謝謝。
