### ISSUE TITLE
v2 版本不能伪装反向代理 http post 请求的bug

### ISSUE THREAD

**Issue by nbuhell** [coyove/goflyway#170]
因为代码里面验证包数据的前20byte，会提前读取post请求中的 前20个字节数据，验证失败后，导致提交给http代理时候post body流里面少了20byte的数据 报错。
而1.0中可以正常代理，是因为1.0通过http head来验证是否正常的数据包，这样不会出现这个问题。

另外这个bug修改也简单，http head额外加个验证就可以了

**Comment by coyove** [comment]
你的意思是预读了20字节，所以跟`Content-Length`对不上吗

**Comment by nbuhell** [comment]
是的，会报错 not match Content-Length
