### ISSUE TITLE
Cloudflare域名解析返回IPv6地址，电脑正常，而安卓客户端无法连接的问题。

### ISSUE THREAD

**Issue by TotalAnnihilation** [coyove/goflyway#175]
服务器，电脑，安卓使用的版本均为v2.0.0 rc1
错误日志如下：
11-18 09:47:40.058  3792  4631 I GuardedProcess: 2019-11-18 01:47:40.057 UTC,client.go:541, ERROR ,"Dial failed: dial [2606:4700:30::681c:1c9f]:80, C113, connect: no route to host"
我分析了一下，Cloudflare域名解析会返回IPv6地址，而手机没有接入IPv6网络，导致三层网络不通，http就更谈不上了。
电脑上是可以关闭IPv6协议的，安卓手机没法关或者我不知道怎么关，我用的是小米。
不知道代码层面能解决这个问题吗？在DNS解析的地址里，强制选择IPv4地址建立连接。
当然了，我觉得手机如果接入IPv6网络我认为是可以正常访问的，不过我没那个条件实验。

**Comment by coyove** [comment]
1. 从代码层面上讲，需要接入miekg/dns类似的库来显式的过滤掉AAAA
2. 从系统层面上讲，因为是Android，目前没有什么好方法，可以尝试一下：
a. 安装Termux，以命令行的方式启动goflyway
b. 安装BifrostV，添加一个socks5代理指向本地的goflyway客户端

**Comment by TotalAnnihilation** [comment]
今天上午研究了一上午，终于搞定这个问题了，坑太多了，分享给大家。
cloudflare现在不允许使用web页面来关闭ipv6了，可以使用api关闭，API还是很麻烦的。
1.下载一个curl
https://curl.haxx.se/download.html
根据自己的系统选择，我下载的是
Windows 64 bit | 7.67.0 | binary | the curl project

2.登陆cloudflare拿到自己的api密钥。
https://dash.cloudflare.com/profile/api-tokens
注意，我们需要的是Global API Key，别拿错了。

3.在你curl解压出来的bin文件夹里使用命令行，我的路径是这样的。
D:\curl-7.67.0-win64-mingw\bin
打开这个文件夹，在空白处按住shift点击右键，在此处打开命令窗口。（这里就不加环境变量了，一共就两条命令）
首先运行这一句，获取你的全部域名信息。
curl -X GET "https://api.cloudflare.com/client/v4/zones?match=all"       -H "X-Auth-Email: xxxxx@xxx.com(你的邮箱)"      -H "X-Auth-Key: xxxx(你的Global API Key)"      -H "Content-Type: application/json" 
这里会返回一个json字符串，里面有你的域名对应的id
{"result":[{"id":"xxx（你的域名id）","name":"xxx（你的域名）"
把这个id粘出来，填入下面的命令运行，禁用IPv6功能
curl -X PATCH "https://api.cloudflare.com/client/v4/zones/xxxx(你域名的id)/settings/ipv6"      -H "X-Auth-Email: xxxxx@xxx.com(你的邮箱)"      -H "X-Auth-Key: xxxx(你的Global API Key)"      -H "Content-Type: application/json"     --data "{\"value\":\"off\"}"
注意，最后这一句--data，我写的是windows的格式，由于转义格式不一样，linux的格式是这样的：
--data '{"value":"off"}'

然后就大功搞成了，再也不用管IPv6了，手机也可以开心上网啦。

**Comment by taibin23** [comment]
> 1. 从代码层面上讲，需要接入miekg/dns类似的库来显式的过滤掉AAAA
> 2. 从系统层面上讲，因为是Android，目前没有什么好方法，可以尝试一下：
>    a. 安装Termux，以命令行的方式启动goflyway
>    b. 安装BifrostV，添加一个socks5配置，指向本地的goflyway客户端

在Termux下执行哪个版本的goflyway，什么命令，还需要哪些操作吗，比如在win10端需要添加个bat文件
