### ISSUE TITLE
提一个建议：建议把 国内域名白名单 改成 国内IP白名单，更准确和省力

### ISSUE THREAD

**Issue by ToyoDAdoubi** [coyove/goflyway#18]
我今天在我博客写了个[ GoFlyway的教程](https://doub.io/goflyway-jc1/)，其中一个使用者留言给我了一个建议，我转述并解释：

### IP白名单相比域名白名单的优点：
1. 国内IP段一般不会变动较大（例如 国内IP广播为国外IP，国外IP广播为国内IP），这就意味着维护成本低，而且有现成的网站提供较准确的国内IP段。
2. 国内域名白名单变动太频繁，可以说每天都有大量的国内网站域名建立或关闭，所以域名白名单准确性有限（维护成本也高），或者说只能针对国内常见域名做白名单。

这样对比看，国内IP白名单 使用起来效果更好，所以建议在作者力所能及的情况下，更换 国内域名白名单 为 国内IP白名单 :rofl:

**Comment by coyove** [comment]
内部是有IP判断的，优先级：
1. 客户端首先查域名白名单
  a. 有的话直连
  b. 没有的话查IP
    1. 国外IP走代理
    2. 内网IP直连
    3. 国内IP有可能被污染，向服务端查IP（没有缓存的情况下）
      a. 国外IP走代理
      b. 国内IP直连。
