### ISSUE TITLE
 使用完，关闭后。 无法正常访问国内网站了，重启也不行？

### ISSUE THREAD

**Issue by AlienChao** [coyove/goflyway#182]
使用完，关闭后。 无法正常访问国内网站了，重启也不行？

**Comment by coyove** [comment]
浏览器的proxy设置没改？

**Comment by AlienChao** [comment]
&nbsp;谢谢，后面找到问题了。 电脑的代理被打开没关



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Coyove"<notifications@github.com&gt;; 
发送时间: 2020年4月20日(星期一) 下午3:30
收件人: "coyove/goflyway"<goflyway@noreply.github.com&gt;; 
抄送: "姜胜超"<850773882@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [coyove/goflyway]  使用完，关闭后。 无法正常访问国内网站了，重启也不行？ (#182)





 
浏览器的proxy设置没改？
