### ISSUE TITLE
goflyway使用如何让我不需要客户端和vps手动开启服务才能使用

### ISSUE THREAD

**Issue by jacknesstjh** [coyove/goflyway#19]
goflyway用了几天了，感觉速度还是不错。以下几个疑问请教大家：
1.goflyway是不是特征特别明显，加密方式是否可以放心使用？
2.我需要手动两边开启服务，能不能vps服务器保持开启开机自启，然后后台运行？
比如写成一个service什么的。
第一次玩github不知道这样询问是否合适，希望有人能拯救我。

**Comment by coyove** [comment]
1. 后台运行，写个脚本然后做成service即可
```shell
#启动
nohup ./goflyway -k=KEY > /dev/null 2>&1 &
#停止
pid=$(ps uax | grep "[g]oflyway" | awk '{print $2}')
kill -9 $pid
```
2. 至于安全性，goflyway用的是aes-256-ctr，每次请求生成新的IV，到这一步是很安全的（当然会有信息校验（MAC）的问题，但这是后话了，现在还没这功能）。不安全的地方在于每次请求时Host的加密，iv用的是2字节+用户密钥随机生成的，这2字节随密文一起发送。因为一般人的上网浏览模式相对固定，所以如果嗅探到一个8字节的密文，可以认为有很高几率是google（6字节）+2字节的组合，在收集到足够多的8字节后，这个方法安全性已经很低了……
3. 至于特征检测，我还没做过实验，不过任何方法都有被爆破的可能。所以现在先用着，到时候（谁知道呢）再改 XD

**Comment by jacknesstjh** [comment]
非常感谢你的回复，也解除我心里很多的担忧。从使用角度来说，我发现goflyway非常的不错，我100M移动宽带完全可以跑满，看油土鳖也非常流畅。我很满意。
今天早上把goflyway写成了service，当然是得到很多好心人教我的。也算是我人生第一次写service。现在使用goflyway就非常方便了。只需要在客户端执行命令就可以了。而不是我之前要两边开启服务这么麻烦了。
goflyway是GO语言写的，非常凑巧，我正在自学GO语言，也希望以后可以多向您请教。
