### ISSUE TITLE
目前只能在客户端/服务端设备中安装Go语言环境吗？可以提供各平台编译后的二进制文件吗？

### ISSUE THREAD

**Issue by ToyoDAdoubi** [coyove/goflyway#2]
需要在客户端/服务端设备中安装Go语言环境，这是要麻烦一些的，最好是在Linux x86、x86_64和Windows 32位、64位系统中编译出二进制文件放到releases中，这样下载使用起来更方便。

**Comment by coyove** [comment]
发布了1.0。
不过毕竟是要在服务器上运行的东西，从源码执行更让人放心一些吧。有系统洁癖的话也可以不安装go，直接解压运行../go/bin/go run main.go也行
