### ISSUE TITLE
arm客户端

### ISSUE THREAD

**Issue by JeffJiangHub** [coyove/goflyway#21]
本人go小白，在release版本中能否加入arm版的？

**Comment by coyove** [comment]
我猜你是想部署到路由器上？目前没有mips和arm版本是因为我手头没有设备测试，所以不发布。go本身是可以跨平台cross compile的：
```
GOOS=linux GOARCH=arm go build -o build/goflyway 
```
`GOARCH`后跟架构名，arm、arm64、mips……

**Comment by recall704** [comment]
```
GOOS=linux GOARCH=arm GOARM=7  go build -o build/goflyway cmd/goflyway/main.go
```

编译成功，也能运行，但是不能连接。
终端也没有任何报错，即使 -lv 参数为 dbg

**Comment by coyove** [comment]
终端有什么显示？只有启动画面吗

**Comment by recall704** [comment]
```
goflyway ./goflyway -k passwd -up ip:2007 -l ":4444" 
     __//                   __ _                           
    /.__.\                 / _| |                          
    \ \/ /      __ _  ___ | |_| |_   ___      ____ _ _   _ 
 '__/    \     / _' |/ _ \|  _| | | | \ \ /\ / / _' | | | |
  \-      )   | (_| | (_) | | | | |_| |\ V  V / (_| | |_| |
   \_____/     \__, |\___/|_| |_|\__, | \_/\_/ \__,_|\__, |
 ____|_|____    __/ |             __/ |               __/ |
     " "  cf   |___/             |___/               |___/ 
 
[  0929 13:11:47.092] listening on :4444, upstream is ip:2007
```

**Comment by coyove** [comment]
请在local尝试一下
```
 echo -e "GET / HTTP/1.1\r\nHost:baidu.com\r\n\r\n" | curl "telnet://127.0.0.1:4444"
```
看看结果是否输出`abspath only`

**Comment by recall704** [comment]
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 29 Sep 2017 05:47:40 GMT
Content-Length: 13

abspath only
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
Connection: close
```

**Comment by coyove** [comment]
从结果看，客户端是正常工作了（返回了abspath only），所以这个问题还蛮奇怪的。

用浏览器连接，比如chrome，输入网址后回车，状态栏里面显示的是什么？如果长时间卡在“waiting for proxy tunnel”或者“等待代理服务器隧道响应”就是客户端的问题了

**Comment by JeffJiangHub** [comment]
和我的情况一样

2017年9月29日 14:11，"Coyove" <notifications@github.com<mailto:notifications@github.com>>写道：

Reopened #21<https://github.com/coyove/goflyway/issues/21>.

**Comment by coyove** [comment]
另外浏览器的行为具体是怎样的呢，输入网址后：
1. 页面卡住，一直loading
2. 页面空白
3. 页面错误，错误码：ERR_XXXXXX_XXXXXX

**Comment by JeffJiangHub** [comment]
手机端的chrome是一直loading
因为不用电脑所以电脑端不知道

2017年9月29日 14:25，"Coyove" <notifications@github.com<mailto:notifications@github.com>>写道：

另外浏览器的行为具体是怎样的呢，输入网址后：

  1.  页面卡住，一直loading
  2.  页面空白
  3.  页面错误，错误码：ERR_XXXXXX_XXXXXX

**Comment by coyove** [comment]
服务端客户端都pull到最新的代码再试试吧。虽然只是“多喝热水”一样的心理安慰，不过之前我也遇到过客户端无响应的情况，跟io有关。有条件的话请用tcpdump抓一下流量
