### ISSUE TITLE
翻不了墙啊

### ISSUE THREAD

**Issue by luckypoem** [coyove/goflyway#22]
hi.

root@gcv:~# lsof -i:8100
COMMAND    PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
goflyway 18202 root    3u  IPv6 28152319      0t0  TCP *:8100 (LISTEN)
root@gcv:~#
可见服务器端运行正常。

本地机器：
yudeMacBook-Air:downloads brite$ ./goflyway -up=my-vps-ip:8100 -k=my-key
     __//                   __ _                           
    /.__.\                 / _| |                          
    \ \/ /      __ _  ___ | |_| |_   ___      ____ _ _   _ 
 '__/    \     / _' |/ _ \|  _| | | | \ \ /\ / / _' | | | |
  \-      )   | (_| | (_) | | | | |_| |\ V  V / (_| | |_| |
   \_____/     \__, |\___/|_| |_|\__, | \_/\_/ \__,_|\__, |
 ____|_|____    __/ |             __/ |               __/ |
     " "  cf   |___/             |___/               |___/ 
 
[  0930 10:12:53.071] listening on :8100, upstream is my-vps-ip:8100

怎么翻不了墙啊？

**Comment by coyove** [comment]
国内网站有没有问题

**Comment by luckypoem** [comment]
hi.
国内网站也打不开。问题何在？

**Comment by coyove** [comment]
页面一直卡在载入，还是载入后显示错误？

**Comment by luckypoem** [comment]
如果设为　socks5代理，则一直卡，打不开网页。如果设为http代理，则浏览器（safari)会下载一个文件,还是打不开网页。
难道是mac客户端程序的问题？

**Comment by coyove** [comment]
有条件的话请pull一下最新的代码运行，因为一是如果你从release下载的话，v1.0是不支持socks5的，二是最近修复了一个bug，也许是对应您这个问题的。

不想麻烦的话可以等我最近会发布的v1.1

**Comment by luckypoem** [comment]
我挂了vpn,然后在mac机器上：
yudeMacBook-Air:gopath brite$ go get -u github.com/coyove/goflyway/cmd/goflyway
yudeMacBook-Air:gopath brite$ which goflyway
/Users/brite/go/bin/goflyway
yudeMacBook-Air:gopath brite$

然后运行goflyway -up=my-vps-ip:8100 -k=my-key
还是翻不了墙。真是匪夷所思

**Comment by coyove** [comment]
两边都加上 `-lv dbg` ，然后访问一下google，正常的话客户端输出 `CONNECT www.google.com:443` 类似的log，服务端是`0 www.google.com:443` 类似的log

**Comment by luckypoem** [comment]
两边都加上了 -lv dbg，然后在mac机器的safari浏览器中设置http proxy为127.0.0.1:8100，这次浏览器能打开国内的网站了，但依旧翻墙失败。如何解决此问题？

**Comment by luckypoem** [comment]
两边都加上了 -lv dbg，然后在mac机器的safari浏览器中设置SOCKS5 proxy为127.0.0.1:8100，这次浏览器也能打开国内的网站了，但依旧翻墙失败

**Comment by coyove** [comment]
加上dbg后，服务端有任何log吗，如果客户端看到了log而服务端没有，则VPS的网络设置可能是问题所在

**Comment by luckypoem** [comment]
加上dbg后,两边都没有log出现。你那里在mac上，真的能用你这个程序翻墙吗

**Comment by coyove** [comment]
抱歉，突然想起dbg的输出必须在HTTP下，SOCKS5不行

**Comment by luckypoem** [comment]
是的，我设为了HTTP代理，但是两边还是没有log出现

**Comment by coyove** [comment]
如果客户端都没有出现任何log，说明浏览器并没有连接到代理，但如果可以浏览墙内网站，又说明连接到了代理，请尝试一下更换浏览器做对照检查

**Comment by luckypoem** [comment]
hi,
先头测试一直是用4g网络，共享给电脑上网。现在改为用wifi上网后，可以翻墙了。不过有些网站打开好慢啊，youtube干脆打不开。是为什么呢

**Comment by coyove** [comment]
测速，http://speedtest.xfinity.com/

**Comment by luckypoem** [comment]
奇迹，今天又试了试，一切ok. youtube也可以看了，还挺流畅

**Comment by luckypoem** [comment]
sorry,搞错了。其实是在用ssr翻的墙。如果改为用goflyway,还是打不开youtube

**Comment by coyove** [comment]
能开google吗

**Comment by luckypoem** [comment]
打不开google/youtube/letscorp.net/blogspot博客／https://www.secretchina.com/ ,http://www.aboluowang.com

其他如http://dongtaiwang.com，http://boxun.com，http://creaders.net，http://www.epochtimes.com，http://www.renminbao.com ，https://www.voachinese.com ，http://www.rfa.org/cantonese/ ，http://cn.rfi.fr ,http://wujieliulan.com 均可打开。

你那里用你这个程序可以打开google/youtube/ letscorp.net /blogspot博客／https://www.secretchina.com/ ,http://www.aboluowang.com 吗？

**Comment by coyove** [comment]
当你访问google的时候，服务端有没有输出`0 www.google.com:443`的讯息？( `-lv dbg`的情况下)

**Comment by sypopo** [comment]
我国内可以打开，国外打不开。同一台服务器搭的SS没问题。

**Comment by sypopo** [comment]
显示

Connection timed out

连接超时

**Comment by coyove** [comment]
@sypopo 
Connection timed out 很有可能表示端口设置错误，请在服务端`netstat`

**Comment by luckypoem** [comment]
不想折腾了。觉得你这个翻墙程序的翻墙机制设计得有点问题，所以不够完善

**Comment by luckypoem** [comment]
我知道为什么了。在mac上，用safari+socks5 proxy翻墙失败，用safari+http proxy只能部分翻墙成功，估计是dns污染所致；用ff+socks5 proxy翻墙,虽然能够成功，但访问youtube还是很慢。改用 chrome+switchyomega+socks5 proxy翻墙,则彻底成功，访问youtube很快。
（在windows上，用ff+socks5 proxy翻墙,能够成功，而且访问youtube很快；但还是建议也使用chrome+switchyomega+socks5 proxy翻墙！

**Comment by coyove** [comment]
这个问题过于诡异了，看来需要找一台mac亲自测一下

**Comment by luckypoem** [comment]
chrome+switchyomega+socks5 proxy模式不稳定。改为chrome+switchyomega+http proxy稳定一些，不过也只能维持半个小时左右，作者能否改善一下程序的稳定性呢？另外我也建议开发一个mac下的gui客户端。也许gui客户端更稳定一些？

**Comment by coyove** [comment]
“不稳定”的具体含义是什么呢，无故退出还是网络错误？

正常来说连续运行应该是没有问题的。另外之前我修了一个客户端的bug，确实会导致crash，如果你代码比较旧的话，可以pull或者用v1.09
![screenshot_20171015-212254 1](https://user-images.githubusercontent.com/3161529/31585163-c0e8215a-b1ef-11e7-85fd-8dbae6f4129f.png)

至于Mac版GUI的开发，目前既无精力也无能力。

**Comment by luckypoem** [comment]
hi.
就是大概运行半小时后，程序自己退出了。

**Comment by coyove** [comment]
那么有可能是跟 #23 一样的问题，请试一下最新的代码

**Comment by luckypoem** [comment]
怎么试最新的代码？是在releases中下载吗？

**Comment by coyove** [comment]
下载版本 1.0.9

另外在goflyway退出之前，有什么错误信息吗

**Comment by luckypoem** [comment]
hi.
goflyway退出后，所显示的错误信息：

[E 1018 08:30:21.108] mux got err: io read timeout
                      ... 1 similar message(s)
[E 1018 09:10:21.934] mux got err: io read timeout
                      ... 2 similar message(s)
[E 1018 09:10:28.105] mux got err: io read timeout
                      ... 1 similar message(s)
[E 1018 09:32:41.707] mux got err: io read timeout
                      ... 2 similar message(s)
[E 1018 09:32:47.759] mux got err: io read timeout


[E 1018 09:56:20.600] mux got err: io read timeout
                      ... 2 similar message(s)
[E 1018 09:56:26.665] mux got err: io read timeout
[E 1018 09:59:32.295] mux got err: io read timeout
[E 1018 09:59:54.976] mux got err: io read timeout
[E 1018 10:02:28.367] mux got err: EOF
                      ... 2 similar message(s)
[E 1018 10:02:30.956] mux got err: io read timeout
                      ... 2 similar message(s)
[E 1018 10:02:37.043] mux got err: io read timeout
                      ... 1 similar message(s)
[E 1018 10:04:04.555] mux got err: io read timeout
[E 1018 10:06:53.679] mux got err: io read timeout
[E 1018 10:06:55.187] mux got err: EOF
                      ... 1 similar message(s)
[E 1018 10:06:58.423] mux got err: io read timeout
                      ... 2 similar message(s)
[E 1018 10:07:04.284] mux got err: EOF
[E 1018 10:08:03.058] mux got err: io read timeout
[E 1018 10:10:01.265] mux got err: EOF
                      ... 1 similar message(s)
[E 1018 10:10:03.542] mux got err: io read timeout
                      ... 2 similar message(s)
[E 1018 10:27:42.020] mux got err: EOF
                      ... 10 similar message(s)
[E 1018 10:27:47.757] proxy pass: http://beacon.sina.com.cn/a.gif?V=2.2.4.20141125&CI=sz:1366x768|dp:24|ac:Mozilla|an:Netscape|cpu:undefined|pf:MacIntel|jv:1.3|ct:unkown|lg:zh-CN|tz:-8|fv:undefined|ja:0&PI=pid:0-9999-0-0-1|st:0|et:2|ref:http%3A//www.nenew.net/|hp:unkown|PGLS:|ZT:|MT:|keys:|dom:316|ifr:0|nld:|drd:|bp:0|url:&UI=vid:4273838854571.6255.1502769737551|sid:4931447973752.241.1506582143561|lv:1506264569832:4:3:2|un:|uo:os.51cto.com,widget.weibo.com,www.nenew.net|ae:|su:0033WrSXqPxfM72-Ws9jqgMF55529P9D9WWvqPkSO2ZaGy5TZqEPeCpY&EX=ex1:|ex2:&gUid_1508293666477, context canceled
[E 1018 10:27:47.758] proxy pass: http://rs.sinajs.cn/tmp.gif?id=show&action=pv&uid=0&url=http%3A%2F%2Fwww.nenew.net%2F&r=1508293666547, context canceled
[E 1018 10:27:52.883] dial 69.61.38.181:8200, C24, socket: too many open files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12e70cd]

goroutine 3051 [running]:
github.com/coyove/goflyway/proxy.(*prefetchReader).readTimeout.func1(0xc4202cd710, 0xc4202cd720, 0xc4204ec140, 0xc4202cc11a, 0x1, 0x1, 0xc4209ae460)
	/Users/yuming/go/gopath/src/github.com/coyove/goflyway/proxy/multiplexer.go:28 +0x2d
created by github.com/coyove/goflyway/proxy.(*prefetchReader).readTimeout
	/Users/yuming/go/gopath/src/github.com/coyove/goflyway/proxy/multiplexer.go:30 +0x106
yudeMacBook-Air:~ brite$

**Comment by luckypoem** [comment]
这个“socket: too many open files”是个死结吗？只能通过重新运行程序来解决？

**Comment by coyove** [comment]
`socket: too many open files` 这个问题是其次
你贴出的log前面有大量的`io timeout`，请问从浏览网页的角度讲有没有非常卡顿？

**Comment by luckypoem** [comment]
浏览网页(翻墙）不卡顿，堪称流畅。只是，客户端只能维持运行半小时左右。

**Comment by coyove** [comment]
更新 v1.0.10 解决 `too many open files`
客户端用这个就行了，服务端1.0.9即可

**Comment by luckypoem** [comment]
下载了mac上的客户端程序（bug fix版），但是也是只能维持运行1个小时左右。只能期待有心人开发一个类似shadowsocksX那样的客户端出来了

**Comment by chocolatesir** [comment]
今天看油管的时候猛拉了下进度条，突然就连不上了，服务端和客户端都是最新的，本地日志全是mux got err: io read timeout，国内的网站打开是正常的，海外网站打开完全不响应，就是空白。已经尝试过重启服务端，修改账户密码，以及重装。有时候打不开的时候浏览器会提示EOF。
![ashampoo_snap_2017 10 24_18h23m02s_001_c--windows-system32-cmd-exe](https://user-images.githubusercontent.com/12197868/31938431-1bb8a46e-b8ea-11e7-8ebb-5e5287168003.png)

**Comment by coyove** [comment]
我猜用的是switchyomega？

**Comment by chocolatesir** [comment]
没错，就是switchyomega，这个有什么影响么？之前是正常的。

**Comment by coyove** [comment]
bug不一定在switchyomega ，不过我日常也是用它+chrome，有时会在短时间内看到大量的io timeout，浏览器卡了一会儿然后正常工作，换用firefox就没问题。目前原因还没查清楚XD。

EOF要么是服务端与目标网站通信时遇到了tcp reset，要么是客户端与浏览器通信时遇到了问题。如果长时间或反复遇到EOF，请打开`-lv dbg`记录日志，或者抓包，以判断到底是服务端还是客户端的问题。

**Comment by luckypoem** [comment]
@chocolatesir ，有问题的话，重启客户端。我觉得这个程序除了每半个小时要重启一下客户端外，翻墙速度非常不错。感觉仅次于ss.对作者的心血深表感谢！

**Comment by luckypoem** [comment]
如果用crontab每半小时重启客户端，该怎么写命令呢？

**Comment by coyove** [comment]
脚本：ps，找到pid，kill，再启动。然后把脚本放到crontab里，间隔20分钟
