### ISSUE TITLE
我在ubuntu的客户端运行一段时间后自动关闭，第一版似乎没那么容易关。以后更新每次我都重新编译，但是没有一次能坚持一天。

### ISSUE THREAD

**Issue by loveproe** [coyove/goflyway#23]
服务端倒是没有自动关闭。我查看了log发现如下
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4743f9]

goroutine 58029 [running]:
panic(0x709a80, 0xc4200120a0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coyove/goflyway/proxy.(*prefetchReader).readTimeout.func1(0xc422b014b0, 0xc422b014c0, 0xc4218de400, 0xc421434340, 0x1, 0x1, 0xc4225fe770)
        /home/sky/work/soft/go/src/github.com/coyove/goflyway/proxy/multiplexer.go:28 +0x29
created by github.com/coyove/goflyway/proxy.(*prefetchReader).readTimeout
        /home/sky/work/soft/go/src/github.com/coyove/goflyway/proxy/multiplexer.go:30 +0x106

**Comment by coyove** [comment]
golang的版本是?

**Comment by loveproe** [comment]
客户端在虚拟机里面，没有安装golang。在服务端的vps用go1.7编译的。但是用你release的1.09的，一样自动关闭客户端。

**Comment by coyove** [comment]
该问题无法重现(ubuntu 16.04)，不过从错误信息可以推断出来确实存在bug
请pull最新代码再测试一下 （fix in #ae64e67）

**Comment by loveproe** [comment]
10个小时没断，现在在出现卡住不能解析的情况的时候，进程没有直接关闭。但是在打不开网页的情况时候，会出现下面的错误（192.168.1.188是我的路由器ip).
[E 1007 20:42:39.057] dial, lookup storage.jd.com on 192.168.1.188:53: dial udp 192.168.1.188:53: socket: too many open files
[E 1007 20:42:39.057] dial, lookup miaosha.jd.com on 192.168.1.188:53: dial udp 192.168.1.188:53: socket: too many open files
[E 1007 20:42:39.057] dial, lookup www.3.cn on 192.168.1.188:53: dial udp 192.168.1.188:53: socket: too many open files
[E 1007 20:42:39.057] dial, lookup storage.jd.com on 192.168.1.188:53: dial udp 192.168.1.188:53: socket: too many open files
[E 1007 20:42:39.057] dial, lookup fd.3.cn on 192.168.1.188:53: no such host
                      ... 3 similar message(s)
[E 1007 20:42:39.058] dial, lookup f.3.cn on 192.168.1.188:53: dial udp 192.168.1.188:53: socket: too many open files
[E 1007 20:42:39.059] dial 111.13.29.228:443, C24, socket: too many open files
[E 1007 20:42:40.442] io.copy 15s: write 192.168.1.240:52405, C32, write: broken pipe
[E 1007 20:42:49.290] io.copy 8s: write 192.168.1.240:52412, C32, write: broken pipe
[E 1007 20:42:50.356] listener: accept [::]:8100, C24, accept4: too many open files

然后过十几秒后会恢复，但是这种中断的情况的确很常见。

**Comment by coyove** [comment]
你是在路由器上自建了一个DNS吗，看错误是goflyway尝试查询IP，发生了too many open files

**Comment by loveproe** [comment]
是的，我用的是ledex64 koolshare的软路由。他为了防止dns污染用了chromecast接替局域网的DNS解析。国内用运营商的国外用4个8

**Comment by coyove** [comment]
个人觉得系统设置的open files limit少说也有几千，一般上网浏览并行发出的DNS query不可能把这么多耗光的。如果用ss的udp over tcp，确实有那么点可能出现堵塞的情况。如果不是这个原因，请在goflyway卡住的时候运行`ss`，看看它到底在请求什么。

**Comment by loveproe** [comment]
谢谢你帮助，我计划关闭路由器的dns劫持来测试下。我是一台微主机24小时开机，里面安装了win10.用hyper-v虚拟了软路由和1个ubuntu14.04.我的路由器的ss一直开着gfwlist模式，台式机一直用这个方式比较方便。用你的goflyway代理在我的ubuntu虚拟机里面运行客户端,这样给我的手机不管是安卓还是iphone做http代理非常方便使用国外代理模式，速度很不错。
