### ISSUE TITLE
udp转发打不开

### ISSUE THREAD

**Issue by JJins** [coyove/goflyway#26]
服务器端使用参数./goflyway -k=KEY -l=":80" -u 80，无法启动，显示
flag provided but not defined: -u

**Comment by JJins** [comment]
./goflyway -k=KEY -l=":80" -udp="80"
这样好像就能打开了……跟readme里不一样啊

**Comment by coyove** [comment]
服务端也是`-udp`，不是`-u`，wiki已改正，感谢
