### ISSUE TITLE
客户端域名支持

### ISSUE THREAD

**Issue by JeffJiangHub** [coyove/goflyway#27]
客户端-up后能否加域名与端口，能否通过cloudflare来隐藏vps真实ip

**Comment by coyove** [comment]
cloudflare并不支持HTTP隧道，所以不行
目前gdev分支下有MITM代理的代码，在这个模式下可以使用一般的HTTP代理作为前置：`客户端 -> HTTP代理 -> 服务端`，但即便是这种模式也依旧不能用cloudflare
