### ISSUE TITLE
You don't have permission to access "http://support.apple.com/" on this server.

### ISSUE THREAD

**Issue by fudingyu** [coyove/goflyway#30]
Access Denied

You don't have permission to access "http://support.apple.com/" on this server.
Reference #18.e8680317.1508762307.ebd1363

**Comment by coyove** [comment]
什么浏览器/插件？
直接在服务端`curl -v http://support.apple.com/`有什么输出

**Comment by fudingyu** [comment]
Chrome + Switchy Omega

I use Google Cloud VPS can't access support.apple.com, but I use other one VPS can access it.

~$ curl -v http://support.apple.com/
*   Trying 23.50.23.118...
* Connected to support.apple.com (23.50.23.118) port 80 (#0)
> GET / HTTP/1.1
> Host: support.apple.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Server: AkamaiGHost
< Mime-Version: 1.0
< Content-Type: text/html
< Content-Length: 266
< Expires: Wed, 25 Oct 2017 10:20:46 GMT
< Date: Wed, 25 Oct 2017 10:20:46 GMT
< Connection: close
< Cache-Control: no-siteapp
< 
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;support&#46;apple&#46;com&#47;" on this server.<P>
Reference&#32;&#35;18&#46;a2ef54b8&#46;1508926846&#46;92056f6
</BODY>
</HTML>
* Closing connection 0

**Comment by coyove** [comment]
Your curl result showed that your vps has been banned from Apple
