### ISSUE TITLE
客户端频繁提示  [E 1102 23:33:46.783] mux got err: io read timeout   ... 2 similar message(s)  

### ISSUE THREAD

**Issue by goxofy** [coyove/goflyway#33]
windows和linux客户端均如此，服务端没有任何特殊或者错误输出

**Comment by coyove** [comment]
如果出现该错误时浏览器卡住/缓慢/显示空白页，请更换浏览器代理工具再试
如果该错误并不影响正常浏览，则可以忽略，没什么大事

**Comment by goxofy** [comment]
谢谢，另外能否编译一个chrome os里能跑的版本~

**Comment by coyove** [comment]
chrome os 不能用 linux 版本吗
