### ISSUE TITLE
web管理默认的端口8101不可以更改

### ISSUE THREAD

**Issue by yyysuo** [coyove/goflyway#39]
看了一下教程，没有提到可以改web管理端口的参数，但是如果windows里面不同配置开多个进程的话，默认的web管理都是8101端口，这样就只能开1个了，请问有什么解决办法吗?

**Comment by coyove** [comment]
使用 `-web-port=12345` 设置，`-web-port=0` 关闭

**Comment by yyysuo** [comment]
问题解决了，非常感谢。
