### ISSUE TITLE
前置代理用的是CNTLM，请问该怎么进行设置

### ISSUE THREAD

**Issue by Hyhyx** [coyove/goflyway#42]
goflyway.exe -k=password -up="http://[usr:pwd@]10.187.45.133:3128/119.29.188.55:8100"
使用这种方式也没有成功

**Comment by Hyhyx** [comment]
goflyway.exe -k=password -up="http://[@10.187.45.133:3128/119.29.188.55:8100"

**Comment by coyove** [comment]
目前还不支持ntlm认证
