### ISSUE TITLE
failed to read ACL config    err:open chinalist.txt:the system can not find the file specified

### ISSUE THREAD

**Issue by yyysuo** [coyove/goflyway#46]
现象：windows端同时开2个goflyway进程，连接相同的服务器IP和端口，一个进程为全局，另一个进程指定本地ACL规则文件，都可以正常使用，是不是goflyway windows客户并不支持多个进程这种使用方式呢？io错误是不是本地IP到VPS IP之间丢包造成的？

进程1-全局错误：
failed to read ACL config     （并未指定ACL文件，见后面的进程1配置）
err:open chinalist.txt:the system can not find the file specified
i/o timeout

进程2-ACL错误：
i/o timeout

环境：windows 10 pro 1709 16299 X64
浏览器：Chrome X64
服务端：v1.1.0 alpha
客户端：v1.1.0 alpha
客户端进程1：CreateObject("WScript.Shell").Run "P:\GoFlyWayBWG\goflyway.exe -g -k=pw -up=myip:1300 -l=:8200 -web-port=8201",0
客户端进程2：CreateObject("WScript.Shell").Run "P:\GoFlyWayBWG\goflyway.exe -k=pw -up=myip:1300 -l=:8300 -web-port=8301 -acl P:\GoFlyWayBWG\nobanAD.acl",0

![default](https://user-images.githubusercontent.com/10081071/35601219-d1457e7c-066c-11e8-9527-379a85115abd.jpg)

![acl](https://user-images.githubusercontent.com/10081071/35601224-d6c3117a-066c-11e8-8932-9e502fbc19d7.jpg)

**Comment by coyove** [comment]
i/o timeout 表示无法连接服务端。一般来说是本地到VPS之间网络的问题。
本地多进程对此是没有影响的

**Comment by yyysuo** [comment]
failed to read ACL config （并未指定ACL文件，见后面的进程1配置）是怎么回事呢？我没有指定acl文件，为什么会报这个错误呢？

**Comment by coyove** [comment]
chinalist.txt 是特殊的acl，没有指定acl时goflyway就会去同目录找这个文件，如果失败则会显示`failed to read ACL config`

**Comment by yyysuo** [comment]
您可以看一下我的截图，我开启2个CMD命令进入到同一个goflyway目录，分别运行主题中的进程1和进程2命令启动2个goflyway进程，进程2没有报错，读取到了chinaiplist.txt和acl文件，说明chinaiplist.txt和acl文件是没有问题的，进程1就读取不到，自从运行过进程1的命令之后，运行进程2的命令就再也读取不到chinaiplist.txt了，并且命令中不指定acl文件，也报读取不到acl文件的错误。

**Comment by yyysuo** [comment]
-alc命令一旦执行，以后在windows中再运行goflyway时，必须指定acl规则文件吗？不指定就会报cannot read acl错误？

**Comment by coyove** [comment]
从图1的报错来看，同目录下确实没chinalist.txt这个文件

**Comment by yyysuo** [comment]
我把文件夹文件列表和两个CMD窗口截在同一张图里面了，您帮忙看一下。
![default](https://user-images.githubusercontent.com/10081071/35613272-967ad7a8-06a6-11e8-90cc-3402a988a741.jpg)

**Comment by coyove** [comment]
个人猜测你用vbs脚本启动goflyway的时候当前目录（cwd）不对，所以找不到chinalist.txt。
你试试`-acl P:\GoFlyWayBWG\chinalist.txt`

**Comment by yyysuo** [comment]
非常感谢，确实是这个问题。
