### ISSUE TITLE
Cannot build go flyway

### ISSUE THREAD

**Issue by surereddy** [coyove/goflyway#48]
hello sir i have this error when i try github.com/coyove/tcpmux
goworkspace/src/github.com/coyove/tcpmux/dial.go:24:4: undefined: rand.Rand
Sir is it possible to give binary release for 32 bit linux please

**Comment by coyove** [comment]
goflyway: git checkout gdev

**Comment by surereddy** [comment]
Sir is it possible to give me Binary release of 32 bit linux kindly

**Comment by coyove** [comment]
Please goto `releases` and find what you want.
