### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by igoodvegetablea** [coyove/goflyway#49]
安装时提示在`github.com/coyove/tcpmux/dial.go`的第24行使用的rand.Rand未定义
查询import部分，发现并未include系统的`math/rand`，而是引用了手写的`goflyway/blob/master/pkg/rand/`
但是在rand.go文件中并未找到对于Rand方法的声明

**Comment by coyove** [comment]
goflyway repo 里需要 `git checkout gdev`

**Comment by igoodvegetablea** [comment]
好的，已经build完毕，谢谢
