### ISSUE TITLE
最新版本是否支持cloudflare？

### ISSUE THREAD

**Issue by YKitty** [coyove/goflyway#50]
域名已经通过cf加速，也使用了指定的cf端口，但是无法连接，客户端没有任何提示。
看到之前关闭的issue说不支持cf，但是教程里面却有cf模式，有点困惑。

**Comment by coyove** [comment]
客户端命令：`-up="cf:\\HOST:80"`，端口号要指定。

之前的issue好久的了，那时确实不支持cf

**Comment by YKitty** [comment]
确认了服务端和客户端端口一致，80 2082端口都不行
把域名换成ip，用普通模式和websocket是正常的
![80](https://user-images.githubusercontent.com/4428897/36415242-17ae0b10-1660-11e8-8093-a302d3bccf31.jpg)

![2082](https://user-images.githubusercontent.com/4428897/36415250-1e2f60a6-1660-11e8-8cb1-ceaf2c450f4d.jpg)

**Comment by YKitty** [comment]
用cf模式，服务端没有收到请求，80端口也是一样
![c cf](https://user-images.githubusercontent.com/4428897/36419613-63a8c390-166d-11e8-91ad-d77e194eaf9d.jpg)

![s cf](https://user-images.githubusercontent.com/4428897/36419622-6adb63fc-166d-11e8-9e03-9e23cca17bb7.jpg)

用websocket和普通模式则一切正常
![c ws](https://user-images.githubusercontent.com/4428897/36419658-850a2ccc-166d-11e8-997e-562543440a39.jpg)

![s ws](https://user-images.githubusercontent.com/4428897/36419674-9085f810-166d-11e8-973d-fc3bd3d961e2.jpg)

**Comment by coyove** [comment]
cloudflare是否打开了强制https的选项？

**Comment by YKitty** [comment]
把 Always use HTTPS 关了就正常了，谢谢
