### ISSUE TITLE
是否可以或者已经支持绑定域名+反向代理方式伪装？

### ISSUE THREAD

**Issue by ToyoDAdoubi** [coyove/goflyway#52]
我在想，如果Goflyway可以绑定域名，然后再配置一个反向代理某个HTTP网站，然后再套个CF CDN，最后客户端直接连接就是代理，访问域名就是反向代理的网站，感觉可以骗骗GFW什么的。
目前我试了试好像不能绑定域名，所以反向代理都是域名替换为当前服务器IP。。。感觉有点假。

**Comment by coyove** [comment]
这样？

服务端：
```
./goflyway -l=80 -proxy-pass http://127.0.0.1:8080
```
Cloudflare:
```
example.com --> 1.2.3.4，Flexible SSL，不要 Always use HTTPS
```
客户端：
```
./goflyway -up="cf://1.2.3.4:80"
```
这样浏览器访问`https://example.com`时反代8080端口的内容，客户端请求则正常处理

**Comment by ToyoDAdoubi** [comment]
测试可用，谢谢。
