### ISSUE TITLE
能编译一个linux arm32的版本吗？

### ISSUE THREAD

**Issue by hbxntsxw** [coyove/goflyway#53]
如题，我自己在ubuntu 16.4和windows 10中编译都无法通过，显示如下错误：
C:\Users\xwfunny>go build github.com/coyove/goflyway/cmd/goflyway
github.com/coyove/tcpmux
go\src\github.com\coyove\tcpmux\dial.go:24:4: undefined: rand.Rand

所以想请问大神能不能编译一个linux arm32的版本？谢谢！

**Comment by coyove** [comment]
`git checkout gdev`
然后编译

**Comment by hbxntsxw** [comment]
@coyove 成功了，非常感谢！
