### ISSUE TITLE
用编译后的版本，无法连接

### ISSUE THREAD

**Issue by flyingwhitewhale** [coyove/goflyway#6]
在vps上和Windows上分别安装编译后的程序，并启动了程序，
[root@host goflyway]# ./goflyway
     __//                   __ _                           
    /.__.\                 / _| |                          
    \ \/ /      __ _  ___ | |_| |_   ___      ____ _ _   _ 
 '__/    \     / _' |/ _ \|  _| | | | \ \ /\ / / _' | | | |
  \-      )   | (_| | (_) | | | | |_| |\ V  V / (_| | |_| |
   \_____/     \__, |\___/|_| |_|\__, | \_/\_/ \__,_|\__, |
 ____|_|____    __/ |             __/ |               __/ |
     " "  cf   |___/             |___/               |___/ 
 
[WARNING] you are using the default key (-k key)
listening on :8100

浏览器设置为http代理 127.0.0.1:8100

可是上不了网
无法访问此网站

网址为 https://www.google.com/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。
ERR_TUNNEL_CONNECTION_FAILED

**Comment by coyove** [comment]
是否有其他错误信息（服务端&客户端）？

**Comment by flyingwhitewhale** [comment]
很奇怪，客户端和服务端都处于显示listening on状态，浏览器哪怕换普通国内网站也上不去，跟vps防火墙没关系，因为我暂时关掉了。
重新关闭启动测试了下
，发现http网站可以，HTTPS的网站不行

**Comment by flyingwhitewhale** [comment]
访问sina.com.cn
![default](https://user-images.githubusercontent.com/30478118/30267417-168ef1c4-9715-11e7-89fd-6d8b93f4bd3c.JPG)

**Comment by coyove** [comment]
你的浏览器和代理工具是什么？（浏览器原生代理、SwitchyOmega……）

**Comment by flyingwhitewhale** [comment]
chrome 60 +switchyomega

![1](https://user-images.githubusercontent.com/30478118/30268021-ec8cf7f2-9716-11e7-9e3f-5e81d4684383.JPG)

VPS是搬瓦工 centos7 *64 bbr，解压后用./goflyway 启动
客户端goflyway 1.0 windows_amd64  ，启动直接点击goflyway.exe

是否因为我启动程序没加 -Key参数，导致无加密？无法连接HTTPS？

**Comment by coyove** [comment]
默认设置下连tech.sina.com.cn不需要服务端，所以问题在客户端或浏览器
你可以试下在IE里面设置代理，看能否正常工作
![image](https://user-images.githubusercontent.com/3161529/30268702-2429de44-9719-11e7-8c17-e2f7858982cf.png)

**Comment by flyingwhitewhale** [comment]
设置IE，后错误信息如下

无法访问此页面
 
详细信息                             <id id="moreInformation">详细信息</id>
--
错误代码: INET_E_SECURITY_PROBLEM

**Comment by coyove** [comment]
个人认为是个bug，但目前无法重现。有条件的话可以试试从源码运行（客户端）看看结果。

**Comment by flyingwhitewhale** [comment]
为了用大佬这个软件真是拼了老命，google了教程，安装了GO环境，学习了如何启动程序
成功从源码运行客户端，结果如下

![default](https://user-images.githubusercontent.com/30478118/30274094-803e434a-972e-11e7-8f08-76355fc222d3.JPG)


服务器端日志如下

![2](https://user-images.githubusercontent.com/30478118/30274124-a31453e6-972e-11e7-91d9-9371592f9140.JPG)

还是上不了网啊 @coyove

**Comment by coyove** [comment]
客户端-k=KEY相当于用`KEY`做了密码，那么服务端也必须加上-k=KEY
另外看了你第二张截图，终于明白了问题所在：release的包发错了。现在重新上传了release包，请在vps上重新下载对应版本运行（你本地已经在run source了，所以没必要再下载了）

**Comment by flyingwhitewhale** [comment]
很好，重新下载编译后文件，一切OK!!
感谢大佬细心指点！
