### ISSUE TITLE
CDN模式下，Goflyway 服务端经常假死（客户端连接无回应），重启服务端后解决

### ISSUE THREAD

**Issue by ToyoDAdoubi** [coyove/goflyway#62]
这种情况是为什么，需要我提供什么信息？
目前只能通过定时重启服务端来解决这个问题。

**Comment by yangqw** [comment]
+1

**Comment by coyove** [comment]
服务端的详细日志输出：`-lv dbg`

**Comment by ToyoDAdoubi** [comment]
@coyove 
同一时间，客户端日志信息：
```
[_0326/144058.760:client.go(338)] WS^ bing.com:443 (global)
                                  ... 1 similar message(s)
[E0326/144144.000:io.go(80)] bridge 0s: read 127.0.0.1:60355, Connection reset by peer
[_0326/144153.207:io.go(190)] active connections: 2
[_0326/144157.300:client.go(338)] WS^ bing.com:443 (global)
                                  ... 1 similar message(s)
```
服务端日志信息：
```                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
                              ... 1 similar message(s)
[_0326/144321.194:server.go(175)] CONNECT bing.com:443
[_0326/144403.173:io.go(195)] multiplexer state: 0/0
```

我发现在无法连接的情况下，客户端与服务端的日志都会出现 `... 1 similar message(s)` 字样。

因为我是自建了一个 Goflyway 免费账号，是在一个被墙IP的服务器上面搭建的，平时有不少人使用。

我尝试在其他服务器上面搭建，没事用几下，基本没出现这种问题，我怀疑是用的人多，或者处理的数据多了，服务端就容易假死，如果是用起来三天捕鱼，两天晒网的好像出现的几率就低很多。

**Comment by coyove** [comment]
`... 1 similar message(s)` 表示该行与上一行日志内容重复

请往上翻，找到第一条出现的日志

**Comment by kingimg** [comment]
大约三四个人用，
有时服务端服务自动停止退出；
每天服务端假死一次，假死时，有时通过http直接访问访问到伪装的网站，有时80端口都不通了。。
[E0606/083931.806:client.go(232)] clients1.google.com:443: readUntil cannot find
 the pattern: [13 10 13 10]
                                  ... 1 similar message(s)

**Comment by coyove** [comment]
是否使用了前置CDN？如果是的话取消前置并使用`ws://SERVER_IP:PORT`直连服务端，观察此现象的出现条件。并且使用`-lv dbg`输出更详细的日志

**Comment by coyove** [comment]
那么请试着在假死时，在服务端运行的同一vps上开启一个客户端进行本地直连。然后用curl之类的工具测试是否可以正常工作。

**Comment by coyove** [comment]
@ToyoDAdoubi 
新版（1.3或dev）已经试图解决这个问题了，请试一下。

**Comment by ToyoDAdoubi** [comment]
好的，我会更新一下服务端观察一下是否还会出现假死情况。

**Comment by ToyoDAdoubi** [comment]
### 测试条件：
CDN模式，实时链接超过 `50` 个独立IP，实时速度在 `1MB/s ~ 3MB/s` 之间。
具体见：https://tz.toyoo.pw/ 中的 **Free LAG2** 。

### 第一次报告 [10/09 20:31] ：
> 启动时间 `17:11:04` 至当前(20:38)，持续 `3.5` 小时，还没有出现进程假死的情况。

### 第二次报告 [] ：
> 暂无。
---
我会继续观察，如果超过两天还没有出现假死，那就代表修复该问题了。
