### ISSUE TITLE
能将android版的applicationid修改一下吗？

### ISSUE THREAD

**Issue by koolwiki** [coyove/goflyway#69]
如题，谢谢你开发这么好的软件。现有的android版软件的applicationid跟shadowsocks的完全一样，这导致二者无法共存，不太方便。能修改一下软件的applicationid吗？谢谢！

**Comment by hbxntsxw** [comment]
我自己改了，但是还是不行，可能光改这一个不行。

**Comment by coyove** [comment]
试了一下apkrename，单纯的改名似乎是不行的。我也不是很懂这块儿，期待有人解答

**Comment by hbxntsxw** [comment]
@coyove 谢谢你的回复！还有几个关于安卓版cloudflare的疑惑想请教你：
1.安卓版要填服务端ip，端口填50080等，这应该就意味者服务端ip必须没有被墙吧？
2.安卓版客户端和服务端通过50080端口进行了哪方面的通信？
3.建立联系后，大部分代理内容还是通过cloudflare中转的是吗？
谢谢！

**Comment by coyove** [comment]
源ip是不能被墙的，客户端会首先与服务端直连一次获得以cf做前置的地址，也就是你在启动服务端时在`-answer="ws://104.*****"`里写的内容，再以该地址连接。

之所以使用这种变扭的方法，是因为借用了ss的壳，goflyway的相关设置没办法在UI上做出来。而本人android开发水平聊胜于无，实在不想自己写了。

**Comment by hbxntsxw** [comment]
@coyove 你这种方法已经很机智了！我想先在本地搭个服务端，把answer="ws://104.*****"信息传递给客户端，然后再连上被墙的ip理论上应该也可行。再次感谢你带来这个好软件！
