### ISSUE TITLE
安卓版1.2.0 cloudflare 连接失败

### ISSUE THREAD

**Issue by liuxunan10** [coyove/goflyway#75]
下载了安卓客户端，按照说明中使用cloudflare的方式 进行配置，然而不能正常连接，配置如下：
服务端：  ./goflyway -l=0.0.0.0:80 -k=password -answer=ws://cdn_ip:80/server_ip:80
安卓客户端： ip：server_ip  port：50080  password: xxxxx
如果是直接连接server_ip 和 80端口可正常连接。但是这样的话就是直连了

**Comment by coyove** [comment]
请使用`./adb logcat | grep "Guarded"`记录一下日志。
windows命令：`./adb logcat -s "Guarded"`

**Comment by liuxunan10** [comment]
这个是我抓取到的日志（已隐藏自己服务器ip， cdn的ip地址是又ping了一次重新抓出来的）
`04-14 08:30:45.327 27650 27808 I GuardedProcess: WARNING: linker: /data/app/com.github.shadowsocks-1/lib/arm64/liboverture.so: unsupported flags DT_FLAGS_1=0x8000000
04-14 08:30:45.383 27650 27802 I GuardedProcess: * goflyway (build __devel__) 
04-14 08:30:45.384 27650 27802 I GuardedProcess: * launched as client 
04-14 08:30:45.384 27650 27802 I GuardedProcess: * TCP multiplexer enabled, limit: 10 
04-14 08:30:45.433 27650 27802 I GuardedProcess: * failed to read ACL config (but it's fine, you can ignore this message) 
04-14 08:30:45.434 27650 27802 I GuardedProcess: *   err: open chinalist.txt: no such file or directory 
04-14 08:30:45.434 27650 27802 I GuardedProcess: * global proxy: goflyway will proxy everything except private IPs 
04-14 08:30:45.463 27650 27820 I GuardedProcess: WARNING: linker: /data/app/com.github.shadowsocks-1/lib/arm64/libtun2socks.so: unsupported flags DT_FLAGS_1=0x8000001
04-14 08:30:46.125 27650 27802 I GuardedProcess: * get config from the upstream 
04-14 08:30:46.738 27650 27802 I GuardedProcess: * use dummy host [ "my_server_ip":80 ] to connect [ 104.27.145.79:80 ] 
04-14 08:30:46.739 27650 27802 I GuardedProcess: * use WebSocket protocol to transfer data 
04-14 08:30:46.906 27650 27802 I GuardedProcess: * proxy 945CF0 started at [ 0.0.0.0:1080 ], upstream: [ 104.27.145.79:80 ] 
04-14 08:30:46.906 27650 27802 I GuardedProcess: * access client web console at [ 127.0.0.1:1090 ] 
04-14 08:30:47.332 27650 27802 I GuardedProcess: [_0414/003047.231:client.go(505)] WS^ 140.206.160.204:8080 (match-pass) (global)
04-14 08:30:47.433 27650 27802 I GuardedProcess: [_0414/003047.345:client.go(505)] WS^ 104.27.145.79:80 (match-proxy) (global)
04-14 08:30:47.533 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:47.533 27650 27802 I GuardedProcess: [E0414/003047.504:client.go(252)] ws error
04-14 08:30:47.634 27650 27802 I GuardedProcess: [_0414/003047.548:client.go(505)] WS^ 104.27.145.79:80 (match-proxy) (global)
04-14 08:30:47.634 27650 27802 I GuardedProcess: [_0414/003047.548:client.go(505)] WS^ 140.206.160.204:8080 (match-pass) (global)
04-14 08:30:47.634 27650 27802 I GuardedProcess: [E0414/003047.565:client.go(252)] ws error
04-14 08:30:47.735 27650 27802 I GuardedProcess: [_0414/003047.639:client.go(505)] WS^ 104.27.145.79:80 (match-proxy) (global)
04-14 08:30:47.735 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:47.735 27650 27802 I GuardedProcess: [E0414/003047.705:client.go(252)] ws error
04-14 08:30:47.836 27650 27802 I GuardedProcess: [_0414/003047.749:client.go(505)] WS^ 104.27.145.79:80 (match-proxy) (global)
04-14 08:30:47.836 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:47.836 27650 27802 I GuardedProcess: [E0414/003047.763:client.go(252)] ws error
04-14 08:30:47.936 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:47.936 27650 27802 I GuardedProcess: [_0414/003047.851:client.go(505)] WS^ 104.27.145.79:80 (match-proxy) (global)
04-14 08:30:47.936 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:47.936 27650 27802 I GuardedProcess: [E0414/003047.908:client.go(252)] ws error
04-14 08:30:48.037 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:48.037 27650 27802 I GuardedProcess: [_0414/003047.941:client.go(505)] WS^ 104.27.145.79:80 (match-proxy) (global)
04-14 08:30:48.037 27650 27802 I GuardedProcess:                                   ... 1 similar message(s)
04-14 08:30:48.037 27650 27802 I GuardedProcess: [E0414/003047.966:client.go(252)] ws error
`

**Comment by coyove** [comment]
`-answer=ws://cdn_ip:80/server_ip:80`应为
`-answer=ws://cdn_ip:80/server_host:80`

**Comment by liuxunan10** [comment]
OK， 成功了， 我把 -answer=ws://cdn_ip:80/server_host:80 中的server_host改成了自己的域名，可以正常连接了，谢谢啦。
