### ISSUE TITLE
疑似ssl证书问题

### ISSUE THREAD

**Issue by falltree** [coyove/goflyway#76]
系统版本 win10 pro，goflyway版本1.2.0a/1.1.0a，之前都使用正常，直到昨天重新全新安装了win10 pro。发现goflyway不正常，google，youtube无法访问，在chrome里提示ERR_CONNECTION_CLOSED，在firefox则是提示服务器响应时间过长，ca.pem已导入了中间证书后，仍然无法正常。
同时注意到，如果是无ssl证书的地址如www.wenxuecity.com，则可以通过goflyway代理正常访问。

**Comment by coyove** [comment]
请使用`-lv dbg`输出更详细的日志。
如果是证书错误，浏览器应该会提示网页不安全，而不是ERR_CONNECTION_CLOSED。
请确定浏览器与客户端之间的连接，客户端与服务端之间的连接正常
请试着访问`http://example.org/`，观察是否可以正常连接

**Comment by falltree** [comment]
使用的doub.io的goflyway tools客户端，加了参数-lv dbg，日志如下。另外现在chrome报错有时显示ERR_TIMED_OUT，有时有ERR_EMPTY

* access client web console at [ 127.0.0.1:8101 ] 
[_0415/220333.642:client.go(363)] CONNECT^ www.youtube.com:443 (global)
... 2 similar message(s)
[_0415/220336.139:client.go(363)] CONNECT^ clients2.google.com:443 (global)
[_0415/220350.036:client.go(363)] CONNECT^ www.youtube.com:443 (global)
[_0415/220409.038:client.go(363)] CONNECT^ www.google.com:443 (global)
[_0415/220410.308:client.go(363)] CONNECT^ www.youtube.com:443 (global)
 ... 3 similar message(s)
[_0415/220416.038:io.go(190)] active connections: 4
[_0415/220418.071:client.go(363)] CONNECT^ clients2.google.com:443 (global)
[_0415/220425[_0415/220516.039:io.go(190)] active connections: 6

**Comment by coyove** [comment]
看了下日志，你使用的还是普通的http代理，所以并不涉及证书的问题。
同时日志显示客户端的请求已经发出，请在服务端也加上`-lv dbg`，观察这些发出的请求是否送达到了服务端。

**Comment by falltree** [comment]
可以确定肯定是电脑端的问题，服务端没有动过任何设置，电脑重装前也正常，重装了，大概半小时后重装完成，用同样的客户端goflyway tool，同样设置来运行，就无法访问youtube了，与此同时，装了1.2.0a的手机端仍然是正常。现在就是奇怪电脑端难道还有什么需要设置的地方？

服务端如下，用****遮掩了一些信息，使用80端口：
root@debian:/usr/local/goflyway# ./goflyway -k=***** -l=":80" -proxy-pass="********" -lv dbg
* goflyway (build 180404051442) 
* launched as server (aka upstream) 
* upstream 0F2A92 started at [ :80 ] 
* alternatively act as a reverse proxy: http://*******
[_0415/235842.074:server.go(173)] CONNECT www.google.com:443
[_0415/235842.130:server.go(173)] CONNECT accounts.google.com:443
[_0415/235842.130:server.go(173)] CONNECT clients2.google.com:443
[_0415/235845.000:server.go(173)] CONNECT www.google.com:443
                                  ... 2 similar message(s)
                                  ... 1 similar message(s)
[_0415/235851.106:server.go(173)] CONNECT duckduckgo.com:443
[_0415/235854.821:server.go(173)] CONNECT www.google.com:443
[_0415/235901.351:server.go(173)] CONNECT duckduckgo.com:443
[_0415/235911.220:server.go(173)] CONNECT www.youtube.com:443
[_0415/235919.627:io.go(190)] active connections: 4
[_0415/235919.630:io.go(195)] multiplexer state: 0/0
[_0415/235923.895:server.go(173)] CONNECT accounts.google.com:443
[_0415/235923.895:server.go(173)] CONNECT www.google.com:443
[_0415/235923.896:server.go(173)] CONNECT clients2.google.com:443
[_0415/235926.931:server.go(173)] CONNECT www.google.com:443
                                  ... 2 similar message(s)
                                  ... 1 similar message(s)

**Comment by coyove** [comment]
那么请试一下使用命令行启动客户端，`goflyway -up="..." -lv dbg`，以排除goflyway tool的问题嫌疑

**Comment by falltree** [comment]
疑难杂症啊，上述服务端日志就是服务端和电脑端都用命令行直接运行的结果，今天再用命令行运行如下。浏览器也换了几个，都是同样情况，用其他代理brook就正常，换goflyway就不行。实在不行只能再重装win10看看了。

PC端：
D:\GoFlyway\1.2.0a>goflyway.exe -k="****" -up="****:80" -l=":****" -web-port="8101" -lv dbg
* goflyway (build 180404051442)
* launched as client
* proxy 0F2A92 started at [ 0.0.0.0:**** ], upstream: [ ****:80 ]
* access client web console at [ 127.0.0.1:8101 ]
[_0416/111354.500:client.go(363)] CONNECT^ clients1.google.com:443 (remote-proxy)
[E0416/111356.280:httpmux.go(40)] prefetch err: read 127.0.0.1:51794, i/o timeout
[_0416/111401.482:client.go(363)] CONNECT^ clients1.google.com:443 (cached)
                                  ... 2 similar message(s)
[_0416/111413.244:client.go(363)] CONNECT^ www.youtube.com:443 (remote-proxy)
[_0416/111414.193:client.go(363)] CONNECT^ clients1.google.com:443 (cached)
                                  ... 1 similar message(s)
[_0416/111419.750:client.go(363)] CONNECT^ www.google.com:443 (remote-proxy)
[_0416/111419.951:client.go(363)] CONNECT^ www.gstatic.com:443 (remote-proxy)
[_0416/111419.980:client.go(363)] CONNECT^ lh3.googleusercontent.com:443 (remote-proxy)
[_0416/111419.986:client.go(363)] CONNECT^ clients5.google.com:443 (remote-proxy)
[_0416/111419.993:client.go(363)] CONNECT^ ogs.google.com:443 (remote-proxy)
[_0416/111419.993:client.go(363)] CONNECT^ clients5.google.com:443 (remote-proxy)
[_0416/111420.322:client.go(363)] CONNECT^ apis.google.com:443 (remote-proxy)
[_0416/111453.807:io.go(190)] active connections: 20
[_0416/111456.712:client.go(363)] CONNECT^ clients1.google.com:443 (cached)
[_0416/111501.035:client.go(363)] CONNECT^ www.google.com:443 (cached)
[_0416/111505.810:client.go(363)] CONNECT^ clients1.google.com:443 (cached)
                                  ... 1 similar message(s)
——————————————————————————————————
服务端
root@debian:/usr/local/goflyway# ./goflyway -k=**** -l=":80" -proxy-pass="http:****" -lv dbg
* goflyway (build 180404051442) 
* launched as server (aka upstream) 
* upstream 0F2A92 started at [ :80 ] 
* alternatively act as a reverse proxy: http:**** 
[_0416/111355.142:server.go(160)] DNS: clients1.google.com 172.217.5.78
[_0416/111355.673:server.go(173)] CONNECT clients1.google.com:443
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
[_0416/111413.883:server.go(160)] DNS: www.youtube.com 216.58.219.46
[_0416/111414.347:server.go(173)] CONNECT www.youtube.com:443
[_0416/111415.350:server.go(173)] CONNECT clients1.google.com:443
                                  ... 1 similar message(s)
[_0416/111420.479:server.go(160)] DNS: www.google.com 216.58.219.4
[_0416/111420.653:server.go(160)] DNS: apis.google.com 216.58.217.206
[_0416/111420.654:server.go(160)] DNS: lh3.googleusercontent.com 216.58.219.1
[_0416/111420.664:server.go(160)] DNS: clients5.google.com 172.217.4.142
                                  ... 1 similar message(s)
[_0416/111420.667:server.go(160)] DNS: ogs.google.com 172.217.14.78
[_0416/111420.669:server.go(160)] DNS: www.gstatic.com 172.217.11.163
[_0416/111420.863:server.go(173)] CONNECT www.google.com:443
[_0416/111421.055:server.go(173)] CONNECT www.gstatic.com:443
[_0416/111421.059:server.go(173)] CONNECT lh3.googleusercontent.com:443
[_0416/111421.063:server.go(173)] CONNECT ogs.google.com:443
[_0416/111421.068:server.go(173)] CONNECT clients5.google.com:443
                                  ... 1 similar message(s)

**Comment by coyove** [comment]
请尝试运行以下命令：
```
./goflyway get -up="..." -v google.com
```
看能否成功

**Comment by falltree** [comment]
貌似成功。加入了-k后是这样的：
D:\GoFlyway\1.2.0a>goflyway get -k=**** -up="****:80" -v google.com
* goflyway (build 180404051442)
* launched as client
* GET http://google.com HTTP/1.1
*
*
* redirect: http://www.google.com/
* GET http://www.google.com/ HTTP/1.1
*
*
* decoding gzip content
* copy body: 3 KB / 4 KB           * HTTP/1.1 200 OK
* Content-Length: 4632
* Cache-Control: private, max-age=0
* Content-Encoding: gzip
* Content-Type: text/html; charset=ISO-8859-1
* Date: Mon, 16 Apr 2018 06:44:25 GMT
* Expires: -1
* P3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
* Server: gws
* Set-Cookie: 1P_JAR=2018-04-16-06; expires=Wed, 16-May-2018 06:44:25 GMT; path=/; domain=.google.com
* Set-Cookie: NID=128=G0aJn7ccDpnhWK7Hm5oUQJjwWdRt10sVQmFvZ446xW12rkYc19aDSatkrUfGv7sWNSWPsRLQthWUxbzWzMnTtzdZPzEhDKb3go_88VaHiMdNpsQMdiQf7mucR7m2MsG3; expires=Tue, 16-Oct-2018 06:44:25 GMT; path=/; domain=.google.com; HttpOnly
* X-Frame-Options: SAMEORIGIN
* X-Xss-Protection: 1; mode=block
*
*
*
* copy body: 4 KB / 4 KB           <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="en"><head><meta content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title><script nonce="mZZjgkcXeuIuvXXakLow4g==">(function(){window.google={kEI:'SUbUWtmmJ4S28AOq4qTICA',kEXPI:'0,201829,1151918,57,473,638,760,86,679,339,74,366,184,533,176,114,174,13,209,15,5,2341420,242,185,32,329294,1294,12383,2349,2506,32692,16114,316,1252,7,1381,7,7798,1402,5281,1100,3101,234,2,2,1624,515,2466,2196,363,554,332,332,2102,113,729,885,589,1673,894,313,309,224,2218,130,130,3732,248,208,919,444,694,353,200,2,561,20,353,24,288,1,3,59,311,295,438,618,402,43,325,36,22,2,1,3,276,409,612,283,105,789,489,623,139,11,1,2,263,734,11,143,421,309,423,497,695,2,49,430,38,7,1,2,148,171,242,49,636,8,325,213,770,261,4,719,137,440,19,4,1048,199,413,40,282,2,441,4,314,2,79,1,280,3,1,595,327,95,113,198,103,11,223,25,10,198,230,122,208,218,78,138,818,781,2345429,192,3,69,3686548,1873,672,9,30,8797621,135,4,1572,549,332,441,2,2,1,2,1,1,77,1,1,510,390,207,1,1,1,1,1,204,167,9,438,23,122,36,14,20,20,22311581',authuser:0,kscs:'c9c918f0_SUbUWtmmJ4S28AOq4qTICA',u:'c9c918f0',kGL:'US'};google.kHL='en';})();(function(){google.lc=[];google.li=0;google.getEI=function(a){for(var b;a&&(!a.getAttribute||!(b=a.getAttribute("eid")));)a=a.parentNode;return b||google.kEI};google.getLEI=function(a){for(var b=null;a&&(!a.getAttribute||!(b=a.getAttribute("leid")));)a=a.parentNode;return b};google.https=function(){return"https:"==window.location.protocol};google.ml=function(){return null};google.wl=function(a,b){try{google.ml(Error(a),!1,b)}catch(d){}};google.time=function(){return(new Date).getTime()};google.log=function(a,b,d,c,g){if(a=google.logUrl(a,b,d,c,g)){b=new Image;var e=google.lc,f=google.li;e[f]=b;b.onerror=b.onload=b.onabort=function(){delete e[f]};google.vel&&google.vel.lu&&google.vel.lu(a);b.src=a;google.li=f+1}};google.logUrl=function(a,b,d,c,g){var e="",f=google.ls||"";d||-1!=b.search("&ei=")||(e="&ei="+google.getEI(c),-1==b.search("&lei=")&&(c=google.getLEI(c))&&(e+="&lei="+c));c="";!d&&google.cshid&&-1==b.search("&cshid=")&&(c="&cshid="+google.cshid);a=d||"/"+(g||"gen_204")+"?atyp=i&ct="+a+"&cad="+b+e+f+"&zx="+google.time()+c;/^http:/i.test(a)&&google.https()&&(google.ml(Error("a"),!1,{src:a,glmm:1}),a="");return a};}).call(this);(function(){google.y={};google.x=function(a,b){if(a)var c=a.id;else{do c=Math.random();while(google.y[c])}google.y[c]=[a,b];return!1};google.lm=[];google.plm=function(a){google.lm.push.apply(google.lm,a)};google.lq=[];google.load=function(a,b,c){google.lq.push([[a],b,c])};google.loadAll=function(a,b){google.lq.push([a,b])};}).call(this);google.f={};var a=window.location,b=a.href.indexOf("#");if(0<=b){var c=a.href.substring(b+1);/(^|&)q=/.test(c)&&-1==c.indexOf("#")&&a.replace("/search?"+c.replace(/(^|&)fp=[^&]*/g,"")+"&cad=h")};</script><style>#gbar,#guser{font-size:13px;padding-top:1px !important;}#gbar{height:22px}#guser{padding-bottom:7px !important;text-align:right}.gbh,.gbd{border-top:1px solid #c9d7f1;font-size:1px}.gbh{height:0;position:absolute;top:24px;width:100%}@media all{.gb1{height:22px;margin-right:.5em;vertical-align:top}#gbar{float:left}}a.gb1,a.gb4{text-decoration:underline !important}a.gb1,a.gb4{color:#00c !important}.gbi .gb4{color:#dd8e27 !important}.gbf .gb4{color:#900 !important}
</style><style>body,td,a,p,.h{font-family:arial,sans-serif}body{margin:0;overflow-y:scroll}#gog{padding:3px 8px 0}td{line-height:.8em}.gac_m td{line-height:17px}form{margin-bottom:20px}.h{color:#36c}.q{color:#00c}.ts td{padding:0}.ts{border-collapse:collapse}em{font-weight:bold;font-style:normal}.lst{height:25px;width:496px}.gsfi,.lst{font:18px arial,sans-serif}.gsfs{font:17px arial,sans-serif}.ds{display:inline-box;display:inline-block;margin:3px 0 4px;margin-left:4px}input{font-family:inherit}a.gb1,a.gb2,a.gb3,a.gb4{color:#11c !important}body{background:#fff;color:black}a{color:#11c;text-decoration:none}a:hover,a:active{text-decoration:underline}.fl a{color:#36c}a:visited{color:#551a8b}a.gb1,a.gb4{text-decoration:underline}a.gb3:hover{text-decoration:none}#ghead a.gb2:hover{color:#fff !important}.sblc{padding-top:5px}.sblc a{display:block;margin:2px 0;margin-left:13px;font-size:11px}.lsbb{background:#eee;border:solid 1px;border-color:#ccc #999 #999 #ccc;height:30px}.lsbb{display:block}.ftl,#fll a{display:inline-block;margin:0 12px}.lsb{background:url(/images/nav_logo229.png) 0 -261px repeat-x;border:none;color:#000;cursor:pointer;height:30px;margin:0;outline:0;font:15px arial,sans-serif;vertical-align:top}.lsb:active{background:#ccc}.lst:focus{outline:none}</style><script nonce="mZZjgkcXeuIuvXXakLow4g=="></script><link href="/images/branding/product/ico/googleg_lodp.ico" rel="shortcut icon"></head><body bgcolor="#fff"><script nonce="mZZjgkcXeuIuvXXakLow4g==">(function(){var src='/images/nav_logo229.png';var iesg=false;document.body.onload = function(){window.n && window.n();if (document.images){new Image().src=src;}
if (!iesg){document.f&&document.f.q.focus();document.gbqf&&document.gbqf.q.focus();}
}
})();</script><div id="mngb"> <div id=gbar><nobr><b class=gb1>Search</b> <a class=gb1 href="http://www.google.com/imghp?hl=en&tab=wi">Images</a> <a class=gb1 href="http://maps.google.com/maps?hl=en&tab=wl">Maps</a> <a class=gb1 href="https://play.google.com/?hl=en&tab=w8">Play</a> <a class=gb1 href="http://www.youtube.com/?gl=US&tab=w1">YouTube</a> <a class=gb1 href="http://news.google.com/nwshp?hl=en&tab=wn">News</a> <a class=gb1 href="https://mail.google.com/mail/?tab=wm">Gmail</a> <a class=gb1 href="https://drive.google.com/?tab=wo">Drive</a> <a class=gb1 style="text-decoration:none" href="https://www.google.com/intl/en/options/"><u>More</u> &raquo;</a></nobr></div><div id=guser width=100%><nobr><span id=gbn class=gbi></span><span id=gbf class=gbf></span><span id=gbe></span><a href="http://www.google.com/history/optout?hl=en" class=gb4>Web History</a> | <a  href="/preferences?hl=en" class=gb4>Settings</a> | <a target=_top id=gb_70 href="https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=http://www.google.com/" class=gb4>Sign in</a></nobr></div><div class=gbh style=left:0></div><div class=gbh style=right:0></div> </div><center><br clear="all" id="lgpd"><div id="lga"><img alt="Google" height="92" src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png" style="padding:28px 0 14px" width="272" id="hplogo" onload="window.lol&&lol()"><br><br></div><form action="/search" name="f"><table cellpadding="0" cellspacing="0"><tr valign="top"><td width="25%">&nbsp;</td><td align="center" nowrap=""><input name="ie" value="ISO-8859-1" type="hidden"><input value="en" name="hl" type="hidden"><input name="source" type="hidden" value="hp"><input name="biw" type="hidden"><input name="bih" type="hidden"><div class="ds" style="height:32px;margin:4px 0"><input style="color:#000;margin:0;padding:5px 8px 0 6px;vertical-align:top" autocomplete="off" class="lst" value="" title="Google Search" maxlength="2048" name="q" size="57"></div><br style="line-height:0"><span class="ds"><span class="lsbb"><input class="lsb" value="Google Search" name="btnG" type="submit"></span></span><span class="ds"><span class="lsbb"><input class="lsb" value="I'm Feeling Lucky" name="btnI" onclick="if(this.form.q.value)this.checked=1; else top.location='/doodles/'" type="submit"></span></span></td><td class="fl sblc" align="left" nowrap="" width="25%"><a href="/advanced_search?hl=en&amp;authuser=0">Advanced search</a><a href="/language_tools?hl=en&amp;authuser=0">Language tools</a></td></tr></table><input id="gbv" name="gbv" type="hidden" value="1"></form><div id="gac_scont"></div><div style="font-size:83%;min-height:3.5em"><br></div><span id="footer"><div style="font-size:10pt"><div style="margin:19px auto;text-align:center" id="fll"><a href="/intl/en/ads/">Advertising�Programs</a><a href="/services/">Business Solutions</a><a href="https://plus.google.com/116899029375914044550" rel="publisher">+Google</a><a href="/intl/en/about.html">About Google</a></div></div><p style="color:#767676;font-size:8pt">&copy; 2018 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p></span></center><script nonce="mZZjgkcXeuIuvXXakLow4g==">(function(){window.google.cdo={height:0,width:0};(function(){var a=window.innerWidth,b=window.innerHeight;if(!a||!b){var c=window.document,d="CSS1Compat"==c.compatMode?c.documentElement:c.body;a=d.clientWidth;b=d.clientHeight}a&&b&&(a!=google.cdo.width||b!=google.cdo.height)&&google.log("","","/client_204?&atyp=i&biw="+a+"&bih="+b+"&ei="+google.kEI);}).call(this);})();</script><div id="xjsd"></div><div id="xjsi"><script nonce="mZZjgkcXeuIuvXXakLow4g==">(function(){function c(b){window.setTimeout(function(){var a=document.createElement("script");a.src=b;google.timers&&google.timers.load.t&&google.tick("load",{gen204:"xjsls",clearcut:31});document.getElementById("xjsd").appendChild(a)},0)}google.dljp=function(b,a){google.xjsu=b;c(a)};google.dlj=c;}).call(this);if(!google.xjs){window._=window._||{};window._DumpException=window._._DumpException=function(e){throw e};window._F_installCss=window._._F_installCss=function(c){};google.dljp('/xjs/_/js/k\x3dxjs.hp.en_US.4rdGDP6sheg.O/m\x3dsb_he,d/am\x3dVDA2/rt\x3dj/d\x3d1/t\x3dzcms/rs\x3dACT90oEkb0BpGibxEqRda1WiwVG3n0Ry0Q','/xjs/_/js/k\x3dxjs.hp.en_US.4rdGDP6sheg.O/m\x3dsb_he,d/am\x3dVDA2/rt\x3dj/d\x3d1/t\x3dzcms/rs\x3dACT90oEkb0BpGibxEqRda1WiwVG3n0Ry0Q');google.xjs=1;}google.pmc={"sb_he":{"agen":true,"cgen":true,"client":"heirloom-hp","dh":true,"dhqt":true,"ds":"","ffql":"en","fl":true,"host":"google.com","isbh":28,"jsonp":true,"msgs":{"cibl":"Clear Search","dym":"Did you mean:","lcky":"I\u0026#39;m Feeling Lucky","lml":"Learn more","oskt":"Input tools","psrc":"This search was removed from your \u003Ca href=\"/history\"\u003EWeb History\u003C/a\u003E","psrl":"Remove","sbit":"Search by image","srch":"Google Search"},"nds":true,"ovr":{},"pq":"","refpd":true,"rfs":[],"sbpl":24,"sbpr":24,"scd":10,"sce":5,"stok":"dbwbt9SVlQcgBqFHDYCwCP-onYM"},"d":{},"ZI/YVQ":{},"U5B21g":{},"DPBNMg":{},"YFCs/g":{}};google.x(null,function(){});(function(){var r=[];google.plm(r);})();(function(){var ctx=[]
;google.jsc && google.jsc.x(ctx);})();</script></div></body></html>
* completed in 0.680s

**Comment by coyove** [comment]
看来服务端客户端之间的连接没有问题。
那么请尝试将客户端监听在0.0.0.0上，然后使用其他设备或系统连接客户端并尝试联网，观察是否可以正常工作。

**Comment by falltree** [comment]
没太明白，监听0.0.0.0意思是电脑端命令行不设服务器ip，然后通过代理上网？这样的结果是无法联网：
电脑命令行执行后：
* goflyway (build 180404051442)
* launched as client
* proxy 0F2A92 started at [ 0.0.0.0:8100 ], upstream: [ 0.0.0.0:8188 ]
* access client web console at [ 127.0.0.1:8110 ]

浏览器设了goflyway代理后显示
proxyconnect tcp: dial tcp 0.0.0.0:80: connectex: No connection could be made because the target machine actively refused it.

**Comment by coyove** [comment]
是客户端：`./goflyway -up="..." -k="..." -l="0.0.0.0:8100"`
这样同一网关——比如家里的wifi——里的其他设备——比如手机——通过设置代理为电脑的ip+8100，来访问网络

**Comment by falltree** [comment]
原来还可以这么玩。刚试了一下，结果有些微妙。
手机以电脑IP+8189端口作为代理，可以上国内新浪，搜狐等网站，也可以上google.com，能搜索，但是youtube，twitter都失败，www.google.com.hk，www.google.com.jp也都失败

D:\GoFlyway\1.2.0a>goflyway -up="***" -k="***" -l="0.0.0.0:8189"
* goflyway (build 180404051442)
* launched as client
* proxy 0F2A92 started at [ 0.0.0.0:8189 ], upstream: [ *** ]
* access client web console at [ 127.0.0.1:8199 ]
[E0416/202114.589:client.go(401)] HTTP forward: http://183.61.109.210:10033/, dial 183.61.109.210:10033, Connection timed out
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
[E0416/202258.077:client.go(314)] dial 110.80.142.121:443, Connection refused
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
[E0416/202303.084:httpmux.go(40)] prefetch err: read 192.168.50.62:60128, i/o timeout
[E0416/202304.238:client.go(314)] dial 110.80.142.121:443, Connection refused
[E0416/202305.269:httpmux.go(40)] prefetch err: read 192.168.50.62:60133, i/o timeout
                                  ... 1 similar message(s)
[E0416/202308.518:client.go(314)] dial 110.80.142.121:443, Connection refused
[E0416/202309.525:httpmux.go(40)] prefetch err: read 192.168.50.62:60136, i/o timeout
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
[E0416/202333.759:client.go(401)] HTTP forward: http://www.google.com/xjs/_/js/k=xjs.qs.zh_CN.xToyD4yhBEs.O/m=RMhBfe/am=gEWyMgVCAgHGFDEBGYy-AEpAEQ/exm=sx,bct,cdos,elog,hsm,jsa,qim,r,d,csi,sb_wiz,aa,abd,async,dvl,foot,ipv6,mu,mhp,qmp,d3l,rQSi2,iP7ptb,if1iFc,yQ43ff,ws9Tlc,uz938c,xpltpb,Fkg7bd,vWNDde,kopZwe,czrJpf,QfiAub,wI7Sfc,HcFEGb,L1AAkb,xPR7tc,y8zIvc,opNw3,Uox2uf,dtPt4d,CiVnBc/rt=j/d=1/ed=1/t=zcms/rs=ACT90oHxLDtnod9J_fF2Qozy5OXSYsNijA, context canceled
[E0416/202336.160:httpmux.go(40)] prefetch err: read 192.168.50.62:60161, i/o timeout
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)
[E0416/202343.290:client.go(314)] dial 110.80.142.121:443, Connection refused
[E0416/202345.176:httpmux.go(40)] prefetch err: read 192.168.50.62:60166, i/o timeout
[E0416/202345.635:client.go(401)] HTTP forward: http://www.google.com/images/branding/product/ico/googleg_lodp.ico, read 45.78.13.5:80, Connection reset by peer
[E0416/202355.978:httpmux.go(40)] prefetch err: read 192.168.50.62:60180, i/o timeout
                                  ... 1 similar message(s)
                                  ... 1 similar message(s)

**Comment by coyove** [comment]
google是通过http访问的吗？

**Comment by falltree** [comment]
不想一直折腾，已重装win10，重装后一切正常。侧面证明是之前系统可能是抽疯造成的，应该不是普遍情况。在这个特殊情况下，系统的问题可能会造成goflyway代理下https的网站访问不正常（似乎是网页内容已经传回，但浏览器无法正确处理，要么当成错误信息，要么当初empty），部分非https的偶尔能够访问。
非常感谢coyove的支持，希望goflyway项目越来越完善。
