### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by cutemanworking** [coyove/goflyway#8]
debian 8.9,
运行：
./goflyway -k hello 

报错：
panic: runtime error: index out of range
goroutine 1 [running]:
main.main()
	/var/www/goflyway/main.go:47 +0xb33

**Comment by coyove** [comment]
请确保chinalist.txt这个文件放在goflyway同目录下

**Comment by cutemanworking** [comment]
服务器端这个chinalist.txt也起作用吗?

**Comment by coyove** [comment]
goflyway是服务端客户端功能一体的，所以都需要chinalist.txt。不过之后会改进一下这个出错信息，或者自动从网络下载这个文件

**Comment by cutemanworking** [comment]
thanks!
