### ISSUE TITLE
关于 CGO_ENABLED 编译设置问题

### ISSUE THREAD

**Issue by mritd** [coyove/goflyway#83]
能否考虑在发布 release 时采用 `CGO_ENABLED=1` 编译? 
目前的问题是: 预编译版本在 docker alpine 中由于 C 库不同导致无法运行，需要手动下载源码重新编译

**Comment by jgit8848** [comment]
可以参考这里的dockerfile来安装库或者直接pull这个镜像
https://hub.docker.com/r/jgit8848/goflyway/~/dockerfile/
我在这个docker容器下是可以正常运行release中最新版的linux_amd64程序的

**Comment by mritd** [comment]
安装glibc 或者兼容包固然可以，但是在预编译直接开启 CGO 完全不需要在镜像中做这些特殊处理
