### ISSUE TITLE
你好请问目前是否支持使用阿里的cdn

### ISSUE THREAD

**Issue by wktadmin** [coyove/goflyway#85]
现在我用的cloudfare的cdn有点慢. 
还是这个命令吗? 
sudo ./goflyway  -k='helloworld' -up='cf://www.****.tk:8080' -l=':1080'
谢谢

**Comment by coyove** [comment]
`cf://xxxx:yy`
是缩写，等效：
`ws://xxxx:yy/xxxx:yy`
阿里的cdn支持websocket？

**Comment by wktadmin** [comment]
多谢, 我试一下
