### ISSUE TITLE
自己修改的goflyway安卓版，支持CDN

### ISSUE THREAD

**Issue by koolwiki** [coyove/goflyway#88]
如题，参考：[Kcp_android](https://github.com/shutup/Kcptun_android)这个项目，通过修改做了一个goflyway的安卓版，需要配合[Postern](https://play.google.com/store/apps/details?id=com.tunnelworkshop.postern&hl=zh)这个软件一起使用。Postern代理服务器栏填127.0.0.1，端口栏填goflyway上面填写的本地端口号（纯端口号，不要带上ip）。

软件下载地址：
https://github.com/koolwiki/goflyway_android/files/2173352/goflyway_v1.0.apk.zip

**Comment by coyove** [comment]
感谢你的帮助，不过把contribution写在issue里实在是很奇怪。
请完善https://github.com/koolwiki/Kcptun_android这个repo（帮助信息等），这样我可以把它写进readme里。

**Comment by koolwiki** [comment]
不懂编程，我对https://github.com/koolwiki/goflyway_android的readme做了一些修改，你指的是这个意思吗？

**Comment by coyove** [comment]
是的，我这边也会更新readme

**Comment by coyove** [comment]
ae8c1d6

**Comment by taibin23** [comment]
> 如题，参考：[Kcp_android](https://github.com/shutup/Kcptun_android)这个项目，通过修改做了一个goflyway的安卓版，可以通过在wifi里面设置代理直接使用，也可以利用[Postern](https://play.google.com/store/apps/details?id=com.tunnelworkshop.postern&hl=zh)这个软件配合一起使用。Postern代理服务器栏填127.0.0.1，端口栏填goflyway上面填写的本地端口号（纯端口号，不要带上ip）。
> 
> 软件下载地址：
> https://github.com/koolwiki/goflyway_android/files/2173352/goflyway_v1.0.apk.zip

传输模式那里填什么？我换了了 kcp， http ，https 都连不上，是配合 BifrostV 的，也按说明填写了
