### ISSUE TITLE
使用疑问

### ISSUE THREAD

**Issue by HyramTang** [coyove/goflyway#9]
使用步骤是这样吗：
1.先在VSP上` go run main.go -k=abcd11 `跑起来
2.然后在本地计算机` go run main.go -k=KEY -up=VPS_IP:172.2.3.4:8100 `，VPS_是直接写8100还是IP地址+8100？
3.然后在IE中设置` 127.0.0.1:8100 `代理

**Comment by coyove** [comment]
go run main.go -k=abcd11 -up="172.2.3.4:8100"
