### ISSUE TITLE
XP下会HTTS证书怎么解决?

### ISSUE THREAD

**Issue by yuhuan21** [coyove/goflyway#96]
我用XP客户端,经过CFCDN,访问油管会提示证书有问题,请问这个怎么解决?十分感谢!
![radmin_2018-09-16_09-58-22](https://user-images.githubusercontent.com/10203925/45592104-3084a600-b997-11e8-941a-8174d3c2c067.png)

**Comment by coyove** [comment]
看看这个证书的内容，是颁给谁的

**Comment by yuhuan21** [comment]
![radmin_2018-09-17_19-10-22](https://user-images.githubusercontent.com/10203925/45619879-7b90dd00-baad-11e8-95bd-c31aaa5fa3eb.png)
![radmin_2018-09-17_19-10-40](https://user-images.githubusercontent.com/10203925/45619880-7e8bcd80-baad-11e8-87d0-4fd3544b545c.png)
![radmin_2018-09-17_19-10-59](https://user-images.githubusercontent.com/10203925/45619882-80559100-baad-11e8-8a51-07f099f4a27e.png)
浏览器是遨游最新版,高速内核,不是IE内核,WIN7下没有这个问题

**Comment by yuhuan21** [comment]
好的,感谢!
