### ISSUE TITLE
how to config for heroku?

### ISSUE THREAD

**Issue by bygreencn** [coyove/goflyway#97]
Any suggestion?

**Comment by coyove** [comment]
websocket模式理论可行，需要改一点代码，你可以尝试部署看看。
一般模式需要tcp长连接，就我搜索到的结果来看heroku不支持，所以这方面也不用考虑了

**Comment by bygreencn** [comment]
听你这么说，基本放弃。不过v2ray的ws模式在heroku的情况到还能勉强接受，毕竟免费跑嘛
